### ISSUE TITLE
There is no visual difference between rares and elites.

### ISSUE THREAD

**Issue by JonathanJamesStewart** [Backupiseasy/ThreatPlates#199]
When a mob is both rare and elite only the rare icon shows. To remedy this elite mob levels should display '{mob_level}+' instead of just '{mob_level}'

**Comment by JonathanJamesStewart** [comment]
I have a fix for this ready but don't have permission to push my branch. It's pretty simple. Change TidyPlatesCore.lua:623 from:
`visual.level:SetText(unit.level)`
to
```
if unit.isElite then
  visual.level:SetText(unit.level .. "+")
else
  visual.level:SetText(unit.level)
end
```

**Comment by Backupiseasy** [comment]
There should be a different coloring for rare and elite mobs (gray and yellow, if I remember correctly). Does that not work?

**Comment by JonathanJamesStewart** [comment]
It does work but if a mob is _both rare and elite_ the rare color overrides the elite color. So the color is gray. This makes it so there is no visual difference between a regular rare mob and an elite rare. Similarly I'm not sure that just making the elite color override the rare as there would then be no visual difference between elites and elite rares. 
I think there needs to be two separate indicators instead of merging them. One for rare and then another for elite.

**Comment by JonathanJamesStewart** [comment]
Any updates on this?

**Comment by Backupiseasy** [comment]
Working on 9.2.0 currently, so there's is not much time currently. I'll take a look at it once all features in 9.2.0 are working as intended.

**Comment by Backupiseasy** [comment]
I might be wrong regarding the +, I think. I find it hard to find a rareelite mob these days, but elite mobs do have a + before there level.

**Comment by JonathanJamesStewart** [comment]
A bronze star would be perfect, I think. Just some visual distinction between the three. For testing there's a rare elite that's in Windshear Crag in Stonetalon Mountains that usually hangs out around 65,54 in Classic. For most text based addons (tooltips, some unit frames) the common denotation for rare is 'R' or 'r' and elite is '+' and for a rare elite is '(r|R)+'.

**Comment by Backupiseasy** [comment]
With v9.2.0, there is now a different color for rareelite mobs as well as a + sign before the level text of elite units.
