### ISSUE TITLE
mount progress bar

### ISSUE THREAD

**Issue by Sooleawa** [Backupiseasy/ThreatPlates#202]
with TPTP plate:
![WoWScrnShot_042720_041549](https://user-images.githubusercontent.com/38173931/80328074-86d9ec00-883e-11ea-9610-b790fa0dc8da.jpg)

Without TPTP plate,  or setting TPTP to use blizzard for neutral mobs:
![WoWScrnShot_042720_042454](https://user-images.githubusercontent.com/38173931/80328273-24cdb680-883f-11ea-9ffa-205e3ce79f03.jpg)

Anyone knows how to have TPTP show this bar too?   if it can not, i would like to report it as a feature enhancement request.

**Comment by Backupiseasy** [comment]
That bar is currently not supported in Threat Plates. There have been requests to add it, see https://github.com/Backupiseasy/ThreatPlates/issues/149, but as there are only very few mobs in BfA, it did not have priority.

**Comment by Backupiseasy** [comment]
This feature is now available in Threat Plates 10.0.x (Widgets - Experience).
