### ISSUE TITLE
Castbar: Show target of current cast

### ISSUE THREAD

**Issue by Backupiseasy** [Backupiseasy/ThreatPlates#206]
* https://www.curseforge.com/wow/addons/tidy-plates-threat-plates?comment=4474
  * Is there a configuration option for displaying who is the current target during casts?
* https://www.curseforge.com/wow/addons/tidy-plates-threat-plates?comment=4495
* https://www.curseforge.com/wow/addons/tidy-plates-threat-plates?comment=4616
  * Is there any way to show the name of the spell target on the castbar? I know Plater has this functionality but can't see it in any of the Threatplates options

**Comment by jmckeown** [comment]
Any idea when this may be released?

**Comment by Backupiseasy** [comment]
Hi Jeremy,

I plan to add that to 9.3, so next non-bugfix version. It will still take
some time as I want to add some more features, see here:
https://github.com/Backupiseasy/ThreatPlates/issues?q=is%3Aopen+is%3Aissue+milestone%3A9.3.0

Regards,

Blacksalsify

Am So., 19. Juli 2020 um 06:21 Uhr schrieb Jeremy McKeown <
notifications@github.com>:

**Comment by gaveer** [comment]
where i can find this option ? i search for it and no luck

**Comment by gaveer** [comment]
@Backupiseasy

**Comment by Backupiseasy** [comment]
The cast target (it's shown under the castbar by default), can be enabled/disabled under General - Castbar - Appearance - Cast Target.

**Comment by Backupiseasy** [comment]
Version 10.0.x of Threat Plates now has a feature to show the target of a cast.
