### ISSUE TITLE
(Bug) SL beta error 9.0.1

### ISSUE THREAD

**Issue by gaveer** [Backupiseasy/ThreatPlates#218]
- **1**.
```
3x ...s_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua:1296: Attempt to register unknown event "UNIT_HEALTH_FREQUENT"
[string "=[C]"]: in function `RegisterEvent'
[string "@TidyPlates_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua"]:1296: in main chunk
```

- Think this event  has been removed and replaced with ```UNIT_HEALTH```

[https://github.com/Stanzilla/WoWUIBugs/wiki/9.0.1-Consolidated-UI-Changes](url)

- **2** 
```
6x ...s_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua:1225: attempt to call method 'UIScaleChanged' (a nil value)
[string "@TidyPlates_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua"]:1225: in function `?'
[string "@TidyPlates_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua"]:940: in function <...s_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua:939>```


```
- **3**
```
3x TidyPlates_ThreatPlates\Core.lua:163: attempt to call method 'EnableCastBars' (a nil value)
[string "@TidyPlates_ThreatPlates\Core.lua"]:163: in function `ReloadTheme'
[string "@TidyPlates_ThreatPlates\Core.lua"]:365: in function <TidyPlates_ThreatPlates\Core.lua:359>
[string "=[C]"]: ?
[string "@Details\Libs\AceAddon-3.0\AceAddon-3.0-12.lua"]:70: in function <...ceDetails\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Details\Libs\AceAddon-3.0\AceAddon-3.0-12.lua"]:527: in function `EnableAddon'
[string "@Details\Libs\AceAddon-3.0\AceAddon-3.0-12.lua"]:620: in function <...ceDetails\Libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:493: in function `UIParentLoadAddOn'
[string "@FrameXML\UIParent.lua"]:540: in function `CombatLog_LoadUI'
[string "@FrameXML\UIParent.lua"]:1355: in function <FrameXML\UIParent.lua:1250> 

```
- Could be Libs related **AceAddon**-3.0.

- **4**
```
300x ...s_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua:975: attempt to index local 'frame' (a nil value)
[string "@TidyPlates_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua"]:975: in function `?'
[string "@TidyPlates_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua"]:940: in function <...s_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua:939>

**Comment by gaveer** [comment]
`2x ...dOns\TidyPlates_ThreatPlates\Widgets\QuestWidget.lua:311: attempt to call upvalue 'GetNumQuestLogEntries' (a nil value)
[string "@TidyPlates_ThreatPlates\Widgets\QuestWidget.lua"]:311: in function 'GenerateQuestCache'
[string "@TidyPlates_ThreatPlates\Widgets\QuestWidget.lua"]:468: in function 'OnEnable'
[string "@TidyPlates_ThreatPlates\Widgets\WidgetHandler.lua"]:283: in function 'EnableWidget'
[string "@TidyPlates_ThreatPlates\Widgets\WidgetHandler.lua"]:227: in function 'InitializeWidget'
[string "@TidyPlates_ThreatPlates\Widgets\WidgetHandler.lua"]:235: in function 'InitializeAllWidgets'
[string "@TidyPlates_ThreatPlates\Core.lua"]:172: in function 'ReloadTheme'
[string "@TidyPlates_ThreatPlates\Core.lua"]:365: in function <TidyPlates_ThreatPlates\Core.lua:359>
[string "=[C]:"]: ?
[string "@Details\Libs\AceAddon-3.0\AceAddon-3.0-12.lua"]:70: in function <...ce\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Details\Libs\AceAddon-3.0\AceAddon-3.0-12.lua"]:527: in function 'EnableAddon'
[string "@Details\Libs\AceAddon-3.0\AceAddon-3.0-12.lua"]:620: in function <...ce\Details\Libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[string "=[C]:"]: in function 'LoadAddOn'
[string "@FrameXML\UIParent.lua"]:493: in function 'UIParentLoadAddOn'
[string "@FrameXML\UIParent.lua"]:540: in function 'CombatLog_LoadUI'
[string "@FrameXML\UIParent.lua"]:1355: in function <FrameXML\UIParent.lua:1250>`

**Comment by gaveer** [comment]
```3x TidyPlates_ThreatPlates\Options-Options.lua:8535: Threat Plates isn't registed with AceConfigRegistry, unable to open config
[string "=[C]"]: ?
[string "@WeakAuras\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:1861: in function `Open'
[string "@TidyPlates_ThreatPlates\Options-Options.lua"]:8535: in function `OpenOptions'
[string "@TidyPlates_ThreatPlates\Commands.lua"]:118: in function `?'
[string "@ElvUI\Libraries\Ace3\AceConsole-3.0\AceConsole-3.0-7.lua"]:94: in function `?'
[string "@FrameXML\ChatFrame.lua"]:5002: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4666: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4702: in function <FrameXML\ChatFrame.lua:4698>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>```

**Comment by Backupiseasy** [comment]
Hi gaveer, thanks for reporting that. I do not have beta access, so I could only start working on a SL version when the PTR for it was enabled last week. I was able to fix most Lua errors (like the above one), so I got a running version. There are probably still some things that are not working (e.g., the Quest widget definitely is not yet working). I hope to release a working version soon though.

**Comment by gaveer** [comment]
- i can be your beta tester . i would be happy to help you  on any kind.

**Comment by Backupiseasy** [comment]
Ok, so here is a first version that at least works on the curren PTR: https://drive.google.com/file/d/1RNH1r7-Hj4Z7Kqin1zQ4PRpIfPod96vM/view?usp=sharing

Any feedback is welcome.

**Comment by gaveer** [comment]
dont have access the to the link .

**Comment by gaveer** [comment]
the last new branch updated was this :
https://github.com/Backupiseasy/ThreatPlates/commit/693a0bab8fa9cee813cd4738aa4b3a4e134bb6d5

**Comment by gaveer** [comment]
its seems working on SL beta version : 9.0.1.35679 
i will keep testing it and update you with any new errors or bugs .

**Comment by Backupiseasy** [comment]
No, actually I forgot to delete this file when I moved the elite overlay into the statusbar. It was not included in the Widgets.xml file anyway.

**Comment by Backupiseasy** [comment]
The following link should work now: https://drive.google.com/file/d/1RNH1r7-Hj4Z7Kqin1zQ4PRpIfPod96vM/view?usp=sharing 

Posting it here to refer other people asking for beta versions to this page.

**Comment by Backupiseasy** [comment]
New version: https://drive.google.com/file/d/1has6XBf5oXm5YUJiW4HTdLSHdMC7KBGU/view?usp=sharing

**Comment by Backupiseasy** [comment]
New Version (Beta3): https://drive.google.com/file/d/1n4rW53kJAMOFQLWolSovJ-92-Ytsqvut/view?usp=sharing

**Comment by extexn** [comment]
Downloaded the version posted 5 days ago. I have an issue with blizzard's nameplate sometimes showing behind TPTP. I've not been able to pinpoint a specific situation when this happens. Bug or is there some setting i've messed up.

**Comment by redpancho** [comment]
> Downloaded the version posted 5 days ago. I have an issue with blizzard's nameplate sometimes showing behind TPTP. I've not been able to pinpoint a specific situation when this happens. Bug or is there some setting i've messed up.
> 
> Edit: Screenshot of bug https://imgur.com/a/GJ2lkno

I'm glad someone else has posted about this, I was very hesitant to do so because it seemed like such a weird issue. However, I have managed to pinpoint that BOTH charge and heroic leap cause this to occur to all visible nameplates.  Toggling nameplates on and off will fix all nameplates.

If more information is needed I can supply videos or screenshots.

**Comment by extexn** [comment]
> > Downloaded the version posted 5 days ago. I have an issue with blizzard's nameplate sometimes showing behind TPTP. I've not been able to pinpoint a specific situation when this happens. Bug or is there some setting i've messed up.
> > Edit: Screenshot of bug https://imgur.com/a/GJ2lkno
> 
> I'm glad someone else has posted about this, I was very hesitant to do so because it seemed like such a weird issue. However, I have managed to pinpoint that BOTH charge and heroic leap cause this to occur to all visible nameplates. Toggling nameplates on and off will fix all nameplates.
> 
> If more information is needed I can supply videos or screenshots.

I have not played a warrior on beta. I also get this bug on classes that do not have a leap or chargetype ability like dk and paladin

**Comment by Backupiseasy** [comment]
Interesting and not sure why this happens, but with this information I should be able to find out easily. Thanks a lot guys.

**Comment by Backupiseasy** [comment]
So, finally found out why this is happening (thanks to Google and kui :)): https://github.com/kesava-wow/kuinameplates2/issues/464. It only does happen on Beta, not on PTR ...

**Comment by Backupiseasy** [comment]
Beta4: https://drive.google.com/file/d/1_j4mktzp3pwG3uGC2hl7hnhNfqRnQDgk/view?usp=sharing - Should fix all the above bugs.

**Comment by Backupiseasy** [comment]
Closing this as 10.0.x for patch 9.0.1 is out now.
