### ISSUE TITLE
Request : Targeting name

### ISSUE THREAD

**Issue by gaveer** [Backupiseasy/ThreatPlates#225]
Hello , where i can find the option to turn the names of the target of my target enemy , i know that only show for tank but i let image tell you what i mean 

9.3.0
![image](https://user-images.githubusercontent.com/45834601/95273861-72196f80-0844-11eb-9560-8bcb9d427a75.png)

9.2.4
![image](https://user-images.githubusercontent.com/45834601/95273972-d4727000-0844-11eb-9283-ece46cb65e0e.png)

**Comment by gaveer** [comment]
* Added an option to show the current target's name on the castbar [Comment #4474, #4495, #4616]

**Comment by gaveer** [comment]
![image](https://user-images.githubusercontent.com/45834601/95277588-7185d680-084e-11eb-8727-2845347dca30.png)
nvm found it

**Comment by Backupiseasy** [comment]
The nameplate unit's target can be enabled/disabled under General - Healthbar - Target. Disable Show text.

The cast target (it's shown under the castbar by default), can be disabled under General - Castbar - Appearance - Cast Target.
