### ISSUE TITLE
Widget error with quest 

### ISSUE THREAD

**Issue by gaveer** [Backupiseasy/ThreatPlates#236]
```
11x Usage: local info = C_QuestLog.GetInfo(questLogIndex)
[string "=[C]:"]: ?
[string "@TidyPlates_ThreatPlates\Widgets\QuestWidget.lua"]:289: in function 'AddQuestCacheEntry'
[string "@TidyPlates_ThreatPlates\Widgets\QuestWidget.lua"]:302: in function 'UpdateQuestCacheEntry'
[string "@TidyPlates_ThreatPlates\Widgets\QuestWidget.lua"]:358: in function '?'
[string "@TidyPlates_ThreatPlates\Widgets\WidgetHandler.lua"]:36: in function <...ns\TidyPlates_ThreatPlates\Widgets\WidgetHandler.lua:30>
```

**Comment by Backupiseasy** [comment]
Is that the whole Lua error you got, gaveer? It would help to see the line in which the error occured (it should be shown in the original Lua error). Also, do you still know with which quest this error occured?

**Comment by gaveer** [comment]
yes i think the error was on flight path , really cant remember  , but this was the whole error

**Comment by Backupiseasy** [comment]
Does the following version fix this issue for you: https://drive.google.com/file/d/1Hr7KjVFf6RLVvhxs8KJrMsX4cJN4Dwdw/view?usp=sharing

**Comment by gaveer** [comment]
i don't know how to produce the error :D

**Comment by Backupiseasy** [comment]
The error seems to happen even with world quests, see https://www.curseforge.com/wow/addons/tidy-plates-threat-plates?comment=4875. So, you might get lucky :) (or not, as I hope it will no longer happen with the above version :))

**Comment by gaveer** [comment]
https://www.curseforge.com/wow/addons/tidy-plates-threat-plates?comment=4895

**Comment by gaveer** [comment]
push update 👍

**Comment by Backupiseasy** [comment]
This issue should now be fixed in the newest version 10.0.2.

**Comment by gaveer** [comment]
https://github.com/Backupiseasy/ThreatPlates/commit/7c86f99e0e63ac1f3250c01377ed4904ead99db1#commitcomment-43496671

**Comment by Backupiseasy** [comment]
Do you still get this error, gaveer? Even with version 10.0.2?
