### ISSUE TITLE
Aura Bug - FIX INCLUDED

### ISSUE THREAD

**Issue by Immovable0bject** [Backupiseasy/ThreatPlates#247]
**Summary:**
After many, many reinstalls of the addon, a complete reinstall of the game itself, and disabling all other addons this is the conclusion I have come to. I hope that this in some way helps the dev(s) to remedy this issue as this is easily the best nameplates addon currently.

**Reproducing the issue:** 
I was trying to use auras in bar mode without an icon. Once I switched characters this would break and never work again on any character, including the one it was originally working on.

**Workaround/Issue Location:** 
Leaving the icon for the aura bar turned on never breaks when changing characters and functions flawlessly throughout gameplay. Apparently the bug lies in the code dealing with the aura bar without the icon.

**Comment by Backupiseasy** [comment]
This is weird, but I should be able to test it based on your information. Not sure when I‘ll be able to do it, as SL is going live today :)

**Comment by Backupiseasy** [comment]
Almost forgot about this one, but I found the underlying bug which is related to the stacks text not being initalized in this situation. Will fix it and re-work that part for 10.0.9.
