### ISSUE TITLE
Is there a way to see Blizzard's new building bars and icons? TP is blocking them.

### ISSUE THREAD

**Issue by Nillx** [Backupiseasy/ThreatPlates#249]
Blizz added some kind of health bars and icons on some buildings, currently TP is hiding them and im wondering if there is away to make them display. Example here: 
Without Threat Plates
![1](https://user-images.githubusercontent.com/34476875/101200821-7b219400-366f-11eb-9905-a5e4b2c57365.JPG)
When i enable TP
![2](https://user-images.githubusercontent.com/34476875/101200823-7bba2a80-366f-11eb-88fe-3a5df699c982.JPG)

**Comment by Backupiseasy** [comment]
I thought that I fixed that (at least for the one unit I know of). Where is this, in Bastion? It should work there with release 10.0.7.

**Comment by Nillx** [comment]
![d](https://user-images.githubusercontent.com/34476875/101213893-c9d92900-3683-11eb-87a3-dd0c215889b8.JPG)
This area. Also the pool near Seat of the Primus is not displaying any icons, only the name.

**Comment by Backupiseasy** [comment]
I guess you need some kind of quest to see it? I don't find it there ...

**Comment by Backupiseasy** [comment]
Weird, it's shows for me though, even with TP enabled. Which version of TP are you using?

**Comment by Nillx** [comment]
version 10.0.4

**Comment by Nillx** [comment]
I can see the HP bar and the icons with 10.0.7 but yeah im getting a lua error too

**Comment by Backupiseasy** [comment]
Good ... and bad :) The Lua error is a result of fixing the special nameplate stuff. I will release a fix as soon as possible.

**Comment by Nillx** [comment]
Thanks and im sorry for wasting your time. Gonna switch to curseforge and see how it is.

**Comment by Backupiseasy** [comment]
Not wasting my time at all. The Lua error was reporting as well and I had no idea why it happend. Now, with this information, I am able to fix it :) So, this report really helped!

**Comment by Nillx** [comment]
Hehe then im happy to help.
