### ISSUE TITLE
Cannot use dash (-) in custom nameplate name

### ISSUE THREAD

**Issue by EdwinHauspie** [Backupiseasy/ThreatPlates#250]
The addon will not accept a name with dash for custom nameplates, example: _Forsworn Squad-Leader_

**Comment by Backupiseasy** [comment]
There's a filter which restricts the characters you can use in names. I guess I have to look into that again - it's basically there to not interfere with Lua pattern matching. For the time being, use "Forsworn Squad*Leader" - that should work.
