### ISSUE TITLE
alpha error

### ISSUE THREAD

**Issue by gaveer** [Backupiseasy/ThreatPlates#252]
- error log 
```
6x ...e\TidyPlates_ThreatPlates\Functions\alpha.lua:165: attempt to call field '?' (a nil value)
[string "@TidyPlates_ThreatPlates\Functions\alpha.lua"]:165: in function 'GetAlpha'
[string "@TidyPlates_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua"]:632: in function <...s_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua:623>
[string "@TidyPlates_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua"]:977: in function <...s_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua:958>
```
 - area 
 51  18 bastion
 - Quest 
http://www.wowhead.com/quest=58585
http://www.wowhead.com/quest=58584
http://www.wowhead.com/quest=58586
- Word Quest 
Might be world quest
http://www.wowhead.com/quest=61520
- This NPC 
 https://www.wowhead.com/npc=176130/anima-forge
- img 
![image](https://user-images.githubusercontent.com/45834601/102989803-4c3c6680-4527-11eb-8fec-afe266d97771.png)

**Comment by Backupiseasy** [comment]
Do you get this error with the 10.0.8 version as well. Will test as soon as possible, but it should be fixed with it.

**Comment by Backupiseasy** [comment]
Ok, so I just checked with 10.0.8 and I don't get any error. It might still be some setting if it happens for you - as previously a Lua error only happend when occlusion transparency was enabled.

**Comment by gaveer** [comment]
i think its fixed , i had 2 quest in top of each others 
- world quest 
- champing quest 

- today the world quest is up and i go there and no error shows up

**Comment by Backupiseasy** [comment]
Ok, thanks. I'll close this issue then. If it resurfaces, just re-open it or create a new one.
