### ISSUE TITLE
Threat support (or other highlight option) for Spiteful mobs that target the player

### ISSUE THREAD

**Issue by cremor** [Backupiseasy/ThreatPlates#256]
Sadly the mobs spawned by the [Spiteful affix](https://www.wowhead.com/affix=123/spiteful) all show like having aggro (as a DPS) on the nameplates, even if they follow other players.

But there is a WeakAura (https://wago.io/hMx86FIwg) that can show an indicator on the nameplates of mobs that follow the player. As far as I can see in its code, it also uses the threat situation. So it seems like there is a way to get the "correct" threat situation for those mobs.

Could you please support this in Threat Plates so that only mobs that follow the player show as having aggro?
At least for DPS/heal. I haven't played this affix as tank yet, but I think best would be to show them all as "fake aggro" so that they are never highlighted for tanks (tanks will never be fixated).

If it isn't possible to support this via the normal threat system/indicators, maybe a custom highlight option would be possible?

**Comment by Backupiseasy** [comment]
Ah, this again. There were similar mobs in BfA (Temple, I think) which had no aggro table. If the WA is able to track this, there seems to be a workaround. I'll look into it. Also, TP has a threat heuristic for that purpose. It's disabled by default I think as (at least outside of dungeons) it is not perfect. But maybe you can test it with this affix.

**Comment by cremor** [comment]
I've already had the "heuristik in instances" option enabled.

**Comment by cremor** [comment]
@Backupiseasy This week is Spiteful week again. Any chance you get some time to work on this? I'd be happy to help if you need to test something.

**Comment by cremor** [comment]
Spiteful will be gone in War Within, so this isn't needed any more.
