### ISSUE TITLE
Headline View Status Text 

### ISSUE THREAD

**Issue by Adartaer** [Backupiseasy/ThreatPlates#263]
Hi I have issue the thing is instead of NPC Tittle like "Fly Master" or "Vendor" Addon show me "Reputation" I can't change it. Anyone can tell me how to fix it please.
![01](https://user-images.githubusercontent.com/78230839/106316583-472cae80-626d-11eb-8a6e-05ce4e4fe246.png)

**Comment by Backupiseasy** [comment]
It's not like that for me. Actually, grunts or headhunters don't have a status text for me which should be correct as the tooltip only shows, e.g., Darkspear Headhunter, Level, ...  and the unit does not have a <> subtitle.

The subtitle is extracted from the tooltip, it's the first line after name. Unless it's level information, then nothing is shown. Now, if the second line in the tooltip for you is reputation, that would explain it. Do you use any tooltip-chaning addon?

**Comment by Adartaer** [comment]
Yeah probably I have a lot of Addons and couple of them can Interact with "ToolTip"

**Comment by Backupiseasy** [comment]
How does your tooltip look like for these units? Can you post a screenshot here?

**Comment by Adartaer** [comment]
![01](https://user-images.githubusercontent.com/78230839/106380845-3c7d3100-63b5-11eb-9a92-4f632d70d824.png)
![02](https://user-images.githubusercontent.com/78230839/106380847-3f782180-63b5-11eb-9ff9-e7054a42ac2c.png)

**Comment by Backupiseasy** [comment]
Do you know what the addon is that adds the reputation information to your tooltip?

**Comment by Adartaer** [comment]
I don't have any idea if I need to guess I will tell that is ElvUI but I'm not sure

**Comment by Backupiseasy** [comment]
Hm, tried ElvUI already, but it did not look like that - at least not with default settings or the ones I found for tooltip. I will look at it again. You could check if the subtext is correct when you disable all addons except Threat Plates.

**Comment by Adartaer** [comment]
With all other addons disabled it's same
![Uploading WoWScrnShot_020121_114229.jpg…]()

**Comment by Adartaer** [comment]
I discover something when I change Profile to Default that's look that:
![WoWScrnShot_020121_120653](https://user-images.githubusercontent.com/78230839/106450892-170c2800-6486-11eb-881e-a2c008e0f9e6.jpg)
With that option uncheck
![WoWScrnShot_020121_120800](https://user-images.githubusercontent.com/78230839/106450984-360aba00-6486-11eb-8c03-4ec8f4b8ccd7.jpg)
But when I change that option it change again
![WoWScrnShot_020121_120858](https://user-images.githubusercontent.com/78230839/106451041-47ec5d00-6486-11eb-9d32-00a79a89b115.jpg)

**Comment by Backupiseasy** [comment]
The difference in the screens above is that headline view is enabled in the last screenshot. Only in headline view, the subtext is NPC Role, Guild. In healthbar view it's health (only shown when below 100%).

The interesting thing is, that I don't get tooltips with reputation info. If it is shown for you with all addons disabled, it should be a CVAR/WoW setting. I just don't know which one ...

**Comment by Adartaer** [comment]
If you figure out something please let me know I'm waiting for the solution 🙂

**Comment by Backupiseasy** [comment]
Still no idea why this is happening ...

**Comment by Backupiseasy** [comment]
Fixed with version 11.1.26 (Fixed a bug where status text did not show the NPC's role when colorblind accessibility features were enabled)
