### ISSUE TITLE
Auras: Change color of nameplate depending on SpellID

### ISSUE THREAD

**Issue by Saxayone** [Backupiseasy/ThreatPlates#265]
Auras: Change color of nameplate depending on SpellID does not seem to work, it works via spell name but not spell ID.

It seems that you enter a spell id, it gets saved as a string within the AsArray value which then can't be read back somewhere.

I manually changed the saved variable out of game to removed the "" around the spellid for the AsArray valuse and it worked correctly.

**Comment by Backupiseasy** [comment]
I did a quick check and I think you are right. I'll fix it in the next release.

**Comment by Backupiseasy** [comment]
Fixed now in release 10.1.3.
