### ISSUE TITLE
LibDogTag error 

### ISSUE THREAD

**Issue by gaveer** [Backupiseasy/ThreatPlates#267]
version : 10.1.4
```
5x invalid key to 'next'
[string "=[C]:"]: in function '(for generator)'
[string "@TidyPlates_ThreatPlates\Libs\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0-20210228122115.lua"]:49: in function <...lates\Libs\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua:46>
[string "@TidyPlates_ThreatPlates\Libs\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0-20210228122115.lua"]:56: in function <...lates\Libs\LibDogTag-Unit-3.0\LibDogTag-Unit-3.0.lua:55>
```
this error show up inside the raid **Castle Nathria** at the trash before**Hungering Destroyer** , maybe cuz counainter in lady inerva

**Comment by Backupiseasy** [comment]
See here: https://www.curseforge.com/wow/addons/threat-plates-classic/issues/39

**Comment by cremor** [comment]
> I guess it's enough if LibDogTag is loaded and it's not important if it's used. I thought that LDT would not process any events when no custom text is used, but that seems to be wrong.

I'm in the same situation. TPTP is the only addon using LibDogTag and I'm not using any dog tags. That's also not so good from a performance point of view. Any chance to only load LibDogTag if it would actually be used?

**Comment by Backupiseasy** [comment]
That's what I intended to do, but obviously it's not working. I guess I need to look into LDT in more detail.
