### ISSUE TITLE
nameplateGlobalScale cvar is being set to 0.4 every reload / log in. Is this a bug?

### ISSUE THREAD

**Issue by dphennessy** [Backupiseasy/ThreatPlates#281]
Here's the profile that it happens on: https://pastebin.com/pycj0nbK
It does not happen if I use the defeault one.

The problem with this is that while the nameplate size looks normal, if the cvar is set to 0.4 then the clickable area is not the same size as the visible nameplate. 
Example gif (I'm spam clicking, but you can see when the onhover zoom animation triggers) ![https://i.gyazo.com/00465c10b8de80efbbbfb478a18bb985.gif](https://i.gyazo.com/00465c10b8de80efbbbfb478a18bb985.gif)

The real size of the nameplates (with cvar set to 0.4) and tptp disabled. So in the gif above the nameplates were actually this size
![https://i.imgur.com/MuG9AAG.png](https://i.imgur.com/MuG9AAG.png)

All my issues would be gone if the cvar just stayed at 1.0 but if i'm using this profile every loading screen / log in / reload sets it back to 0.4

I've been messing around with the settings but I can't figure out what the root of the problem is. I didn't make this profile although I like it very much (while the cvar stays at 1.0 ! ) so I'm unsure if there's some setting I missed because of that. Please say if I can provide any more details.

Edit: Another gif showing the problem
![https://i.gyazo.com/cd08e469917a981350fe6e0b2d512e7c.gif](https://i.gyazo.com/cd08e469917a981350fe6e0b2d512e7c.gif)

**Comment by Backupiseasy** [comment]
It's a feature under Automization that is used to switch nameplates to a smaller size when entering an instance. It's meant for friendly nameplates, but you are right, I think it will reduce the size of enemy nameplates and therefore the clickable area as well. That's not good. For the time being, you can disable that smaller friendly nameplates are used in instances. Then this should no longer happen. 

You might also have to switch between normal / small nameplates in Interface - Names to reset everything, I think.

**Comment by dphennessy** [comment]
Ah brilliant, that was it ty!

**Comment by Backupiseasy** [comment]
In the latest release, 10.1.7, I now removed the feature for small nameplates in instances as there is no way to implement it with side-effects.
