### ISSUE TITLE
Healer Tracker Widget for Headline View - Positioning Bug

### ISSUE THREAD

**Issue by volpemauro** [Backupiseasy/ThreatPlates#283]
The positioning of the Healer Tracker Widget for the Headline View does not work. Instead, the values from the Healthbar View get applied.

**Comment by Backupiseasy** [comment]
Actually, Healer Tracker does not really support headline view. There's options for it, but it never was implemented. I'll fix this. Thanks for reporting it.

**Comment by volpemauro** [comment]
Thx, i would love it <3

**Comment by Backupiseasy** [comment]
You can test the following version: https://drive.google.com/file/d/1MTpss5DU6gWVhw4J5Ll87lwTkUv4i4BG/view?usp=sharing

It's not fully tested, but should work.

**Comment by volpemauro** [comment]
I have tested it and it works as expected. I love it.

**Comment by Backupiseasy** [comment]
I released a new version today (10.1.7) that fixes this issue.
