### ISSUE TITLE
How do I disable the colors for Raid Targets?

### ISSUE THREAD

**Issue by Jakobud** [Backupiseasy/ThreatPlates#294]
There is the option to change the colors of the plates depending on what Raid Target marker/icon is assigned to the target. For example the default for the blue Square makes the nameplate blue.

Is it possible to completely disable this feature? When I'm tanking I want all my nameplates to be either green or red, depending on threat. I don't want the nameplate colors to be defined by the raid targets. For example, super annoying when a red X is assigned to a target and now the nameplate is RED, which normally indicates you have lost threat on it even though you probably haven't.

Just an option to completely disable this color change based on raid icons would be really nice. If it's already in there, I'm just not seeing it.

**Comment by Jakobud** [comment]
Fired it out nevermind. In the options you should move the Target Marker colors section to the Target Markers section instead of under Colors.

**Comment by Backupiseasy** [comment]
Actually, it was there initially, but I wanted to move all colors into one section (so that it can be easier found ... :D). I have to rework options anyway, getting rid of some tabs. That's something I want to do since quite some time, but I can't find the right time do actually change that.
