### ISSUE TITLE
Widget: Aura Stack Count Disabled

### ISSUE THREAD

**Issue by EigenTheory** [Backupiseasy/ThreatPlates#296]
Does the feature for showing buff stack counts not work? I have looked and searched everywhere but in my UI Stack Count is grayed out.

**Comment by Backupiseasy** [comment]
You mean the option to enable/disable the stack count under Auras - Appearance or the settings to configure the stack count font in icon mode? In icon mode, you have to enable "Custom" as style to be able to change fonts. With Square or Wide, everything is fixed and cannot be changed.

**Comment by EigenTheory** [comment]
Okay, thanks, my misunderstanding!

**Comment by Backupiseasy** [comment]
Ok, Just glad to hear that it was no bug.
