### ISSUE TITLE
[QUESTION] How can i add custom totem by my self

### ISSUE THREAD

**Issue by LetsStartDisco** [Backupiseasy/ThreatPlates#313]
Hi, how can i add custom totem by my self, for example Vesper Totem, i can't find totem's list, added icon, but can't add totem in totem vidgets :)

**Comment by Backupiseasy** [comment]
You should be able to define a custom nameplate for this. I am just not sure if custom plates have a higher priority than the (built-in) player totem plates. I would need to check this.

Vesper totem, though, is no player totem right?

**Comment by LetsStartDisco** [comment]
> You should be able to define a custom nameplate for this. I am just not sure if custom plates have a higher priority than the (built-in) player totem plates. I would need to check this.
> 
> Vesper totem, though, is no player totem right?

This is Elemental Shaman totem, from covenant)

**Comment by Backupiseasy** [comment]
I added Vesper Totem to the totem list: https://drive.google.com/file/d/1tk9Ut0nxrFKzmy8b2HTLSZCh4Y2wUhsj/view?usp=sharing

Does this version work for you?

**Comment by Backupiseasy** [comment]
Vesper totem is now available in the totem list in release 10.2.4
