### ISSUE TITLE
ThreatPlates-10.3.0-beta1 issue at login on retail

### ISSUE THREAD

**Issue by EnserNG** [Backupiseasy/ThreatPlates#315]
Date: 2021-12-19 15:18:20
ID: 1
Error occured in: Global
Count: 3
Message: ...s_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua line 1859:
   attempt to call method 'UpdateConfigurationLocalization' (a nil value)
Debug:
   [string "=[C]"]: UpdateConfigurationLocalization()
   [string "@TidyPlates_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua"]:1859: ForceUpdate()
   [string "@TidyPlates_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua"]:1428: ?()
   [string "@TidyPlates_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua"]:1024:
      ...s_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua:1023
Locals:

  BlizRuntimeLib_enUS v9.1.5.90105 <none>
  (ck=fbe)

**Comment by Backupiseasy** [comment]
Is that the only (or first) error message you get?

**Comment by EnserNG** [comment]
First

**Comment by EnserNG** [comment]
Sorry - no access to files at present.  Second error says something about TP being unable to find Cyrillic or something like that.  On an enUS client, so not using anything like that myself.

**Comment by Backupiseasy** [comment]
Ok, that's interesting. I changed something regarding localization, so that might be the issue. But I don't get this error myself.

**Comment by Backupiseasy** [comment]
Still not able to reproduce this. Do you mind sending me your settings file (TidyPlates_ThreatPlates.lua in WTF)? If there is error in the migration code for Auras widget, that might result in something like that.

**Comment by EnserNG** [comment]
Here you go - 
[TidyPlates_ThreatPlates.zip](https://github.com/Backupiseasy/ThreatPlates/files/7747065/TidyPlates_ThreatPlates.zip)

**Comment by Backupiseasy** [comment]
Ok, the settings file seems fine. I don't get an error with this either.

**Comment by EnserNG** [comment]
Let me try the beta, again, and see if there was some transient issue or something.

**Comment by EnserNG** [comment]
Any other ideas? Could just blank the SV, but have become used to how it is set up.

Just tried using a fresh d/l of the beta from CF - same error:

Date: 2021-12-21 22:06:24
ID: 1
Error occured in: Global
Count: 2
Message: ...s_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua line 1859:
   attempt to call method 'UpdateConfigurationLocalization' (a nil value)
Debug:
   [string "=[C]"]: UpdateConfigurationLocalization()
   [string "@TidyPlates_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua"]:1859: ForceUpdate()
   [string "@TidyPlates_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua"]:1428: ?()
   [string "@TidyPlates_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua"]:1024:
      ...s_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua:1023
Locals:

  BlizRuntimeLib_enUS v9.1.5.90105 <none>
  (ck=1059)

**Comment by Backupiseasy** [comment]
Right now I have no idea how to solve it. The method UpdateConfigurationLocalization does exist at this point and that's why it does not result in an error for me. It being nil means (in most cases that I saw so far) that something went wrong earlier, so that the initialization of the addon failed, like, e.g. a big in the settings migration. That's why I asked for that. But then this should never be the first error message (although I had a few cases where the 2nd/3rd one showed the actual error).

**Comment by EnserNG** [comment]
Yeah, sorry for the trouble.  Double-checked and that is the first error of the session. Have no other errors that show from anywhere when running the previous release. Will try to check with only TPTP running and see if that helps. Appreciate your looking into it and your work overall!

**Comment by Backupiseasy** [comment]
In the end, that's what beta is for :) So I am really thankful for people trying it out and reporting this kind of bugs. Although you have to suffer at bit :)

**Comment by EnserNG** [comment]
Ran the Blizz repair just on the off chance that it was something on their end, but same error as the first.  Now it may just be a result of error ID: 1, but perhaps the second error may provide some insight:

Date: 2021-12-30 22:58:34
ID: 2
Error occured in: Global
Count: 10
Message: ...ddOns\TidyPlates_ThreatPlates\Functions\nametext.lua line 22:
   attempt to call upvalue 'TransliterateCyrillicLetters' (a nil value)
Debug:
   [string "=[C]"]: ?
   [string "@TidyPlates_ThreatPlates\Functions\nametext.lua"]:22: SetNameText()
   [string "@TidyPlates_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua"]:718:
      ...s_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua:717
   [string "@TidyPlates_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua"]:787:
      ...s_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua:785
   [string "@TidyPlates_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua"]:358:
      ...s_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua:344
   [string "@TidyPlates_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua"]:424:
      ...s_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua:402
   [string "@TidyPlates_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua"]:1066: ?()
   [string "@TidyPlates_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua"]:1024:
      ...s_ThreatPlates\TidyPlatesInternal\TidyPlatesCore.lua:1023
Locals:

BlizRuntimeLib_enUS v9.1.5.90105 <none>
  (ck=fe6)

**Comment by EnserNG** [comment]
Feeling like a noob - deleted the existing folder and installed the beta and... it works!  Looks like some old file was not happy with the changes, but all good now!! =)

**Comment by Backupiseasy** [comment]
Hm, ok. Normally, when you install via an addon  manager, there should not remain any old files. Not saying that I didn't run into such weird bugs myself. Best case is it really was just that. Will see when I release this version, I guess :)
