### ISSUE TITLE
[All WoW versions] Damage numbers above the ThreatPlates bar?

### ISSUE THREAD

**Issue by Nillx** [Backupiseasy/ThreatPlates#320]
Is it possible to make TP's bar appear under the regular wow damage numbers? Or thats impossible?
![Screenshot 2022-01-23 220248](https://user-images.githubusercontent.com/34476875/150695992-9aec3b47-1715-42c5-9cfc-de2fdfd60c37.png)

**Comment by Backupiseasy** [comment]
As far as I know, that‘s not possible. I did some investigations some time ago and checked with other nameplate addons, but all had the same issue.

**Comment by Nillx** [comment]
Fair enough, i was checking around too and everyone are saying that its impossible to change them as they are part of the 3D world.
