### ISSUE TITLE
Extended Raid Icons support.

### ISSUE THREAD

**Issue by diw1** [Backupiseasy/ThreatPlates#327]
There is 9-16 extended raid icons are available in DBM, 
https://github.com/DeadlyBossMods/DBM-Retail/wiki/%5BAdvanced-Guide%5D-Extended-Raid-Icons-(Obsolete)

As well as in Weakauras 
https://github.com/WeakAuras/WeakAuras2/issues/3473

So I wonder if ThreatPlates could support for this

**Comment by cremor** [comment]
This is no longer possible, Blizzard disabled it. See update in your first link.

**Comment by Backupiseasy** [comment]
Saw that, yeah.
