### ISSUE TITLE
Wotlk update?

### ISSUE THREAD

**Issue by jazminite** [Backupiseasy/ThreatPlates#344]
Any updates for Wrath of the Lich King? Pre-patch is available on the Classic BCC PTR.

**Comment by Backupiseasy** [comment]
Isn't the PTR still on the TBC Classic client version? I just tested and the client id still says TBC Classic. It didn't really look into it, though.

**Comment by jazminite** [comment]
@Backupiseasy - The battle.net client still says _"Public Test Realm (Classic BCC)"_ but it is updated. Here's the official post:
https://us.forums.blizzard.com/en/wow/t/pre-expansion-patch-testing-notes/1298822

**Comment by danjohnso** [comment]
PTR is currently in full wrath classic mode
![image](https://user-images.githubusercontent.com/852995/184934413-ae2ac817-2f9c-49a9-9442-5712e7f9d954.png)

**Comment by Backupiseasy** [comment]
I saw it. The client still returns the WOW_PROJECT_ID for TBC Classic though. Also, Threat Plates still seems to work fine there which probably would not be the case if the client/UI version changes (as was the case for Classic, TBC Classic). I guess I will spend some time in the upcoming days to investigate.

**Comment by Backupiseasy** [comment]
I finally can understand why I assumed that the client is still unchanged: https://github.com/Stanzilla/WoWUIBugs/issues/251

**Comment by Backupiseasy** [comment]
Just FYI, working on it. There should be a first beta version this weekend.

**Comment by Backupiseasy** [comment]
A first beta version for WotLK is now available as 10.5.0-beta2
