### ISSUE TITLE
Threat delta value is multiplied by 100-1000?

### ISSUE THREAD

**Issue by jonerikb** [Backupiseasy/ThreatPlates#346]
The threat delta value seems to be multiplied by 100, compared to the threat values in Details damage meter.

local function GetThreatDelta(unitid, threat_value_func)
.
change: return threat_value_text, threat_value_delta 
to: return threat_value_text, threat_value_delta/100

This fix works for solo play, havent tested all scenarios
![deltavalue](https://user-images.githubusercontent.com/365576/186770320-c26eeec4-e7f5-4c12-85e6-fe00520abc98.png)
.
Based on this image from a raid it seems the delta value is multiplied by around 1000

**Comment by jonerikb** [comment]
Here is some examples of delta threat values after the fix i applied:
![postfix](https://user-images.githubusercontent.com/365576/186980604-66ae4b42-a21f-4b5e-8d98-4993b5f69d67.png)

The numbers seem more realistic, but they are probably lagging slightly behind due to refresh rate.
For some reason, most of the time the tank is shown as the next on threat

**Comment by Backupiseasy** [comment]
As it seems, in Classic the threat value is really 100 times the value it should be. Will fix that. Sorry that it took so long.

**Comment by Backupiseasy** [comment]
I uploaded a new verstion for 10.5.3 (beta1). This should be fixed in this version, see https://www.curseforge.com/wow/addons/tidy-plates-threat-plates/files/4009285 (for Wrath Classic).

**Comment by Backupiseasy** [comment]
This issue is now fixed since version 10.5.3.
