### ISSUE TITLE
LUA error in beta

### ISSUE THREAD

**Issue by Ravenwylde** [Backupiseasy/ThreatPlates#351]
Message: ...dOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua:2047: attempt to call upvalue 'ShouldSkipAuraUpdate' (a nil value)
Time: Thu Sep 15 15:04:59 2022
Count: 4
Stack: ...dOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua:2047: attempt to call upvalue 'ShouldSkipAuraUpdate' (a nil value)
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua"]:2047: in function <...dOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua:2026>

Locals: widget_frame = Frame {
 0 = <userdata>
 Debuffs = Frame {
 }
 CrowdControl = Frame {
 }
 Active = true
 HideAuras = false
 Buffs = Frame {
 }
 Widget = <table> {
 }
 unit = <table> {
 }
}
event = "UNIT_AURA"
unitid = "nameplate1"
is_full_update = <table> {
 updatedAuraInstanceIDs = <table> {
 }
 isFullUpdate = false
}
updated_aura_infos = nil
unit = <table> {
 guid = "Creature-0-2084-2444-2703-196017-0003A355ED"
 isMouseover = false
 class = ""
 IsFocus = false
 IsBossOrRare = false
 level = 62
 red = 1
 levelcolorRed = 1
 unitid = "nameplate1"
 HasUnlimitedAuras = true
 isMini = false
 style = "normal"
 TP_DetailedUnitType = "Neutral"
 isElite = false
 isMarked = false
 isInCombat = false
 threatSituation = "LOW"
 levelcolorBlue = 0
 threatValue = 0
 isBoss = false
 health = 77345
 blue = 0
 name = "Pudgy Riverbeast"
 healthmax = 77345
 isTarget = false
 levelcolorGreen = 0.820000
 NPCID = "196017"
 type = "NPC"
 isTapped = false
 classification = "normal"
 isCasting = false
 IsInterrupted = false
 reaction = "NEUTRAL"
 green = 1
 isRare = false
}
db = <table> {
 DefaultBuffColor = <table> {
 }
 ShowCooldownSpiral = false
 CrowdControl = <table> {
 }
 ShowTargetOnly = false
 FrameOrder = "HEALTHBAR_AURAS"
 FlashWhenExpiring = false
 ShowOmnicCC = false
 SwitchAreaByReaction = true
 ShowInHeadlineView = false
 FlashTime = 5
 ShowAuraType = true
 ShowStackCount = true
 ShowDuration = true
 ShowTooltips = false
 SortReverse = false
 DefaultDebuffColor = <table> {
 }
 Highlight = <table> {
 }
 SortOrder = "TimeLeft"
 Buffs = <table> {
 }
 ON = true
 Debuffs = <table> {
 }
}
unit_is_friendly = false
enabled_buffs = true
enabled_debuffs = true
enabled_cc = true
(*temporary) = nil
(*temporary) = <table> {
 updatedAuraInstanceIDs = <table> {
 }
 isFullUpdate = false
}
(*temporary) = nil
(*temporary) = <function> defined @Interface/AddOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua:1995
(*temporary) = <table> {
 guid = "Creature-0-2084-2444-2703-196017-0003A355ED"
 isMouseover = false
 class = ""
 IsFocus = false
 IsBossOrRare = false
 level = 62
 red = 1
 levelcolorRed = 1
 unitid = "nameplate1"
 HasUnlimitedAuras = true
 isMini = false
 style = "normal"
 TP_DetailedUnitType = "Neutral"
 isElite = false
 isMarked = false
 isInCombat = false
 threatSituation = "LOW"
 levelcolorBlue = 0
 threatValue = 0
 isBoss = false
 health = 77345
 blue = 0
 name = "Pudgy Riverbeast"
 healthmax = 77345
 isTarget = false
 levelcolorGreen = 0.820000
 NPCID = "196017"
 type = "NPC"
 isTapped = false
 classification = "normal"
 isCasting = false
 IsInterrupted = false
 reaction = "NEUTRAL"
 green = 1
 isRare = false
}
(*temporary) = false
(*temporary) = true
(*temporary) = true
(*temporary) = true
(*temporary) = "attempt to call upvalue 'ShouldSkipAuraUpdate' (a nil value)"
Widget = <table> {
 UpdateSettingsIconMode = <function> defined @Interface/AddOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua:2715
 CrowdControl = <table> {
 }
 UnregisterAllEvents = <function> defined @Interface/AddOns/TidyPlates_ThreatPlates/Widgets/WidgetHandler.lua:104
 FilterEnemyDebuffsBySpell = <function> defined @Interface/AddOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua:1247
 WidgetHandler = <table> {
 }
 FilterEnemyBuffsBySpell = <function> defined @Interface/AddOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua:1289
 TEXTURE_BORDER = "Interface\AddOns\TidyPlates_ThreatPlates\Artwork\squareline"
 FilterFriendlyDebuffsBySpell = <function> defined @Interface/AddOns/TidyPlates_ThreatPlates/Widgets/Aur

**Comment by Backupiseasy** [comment]
Beta is not yet supported, so this is to be expected :)

**Comment by Backupiseasy** [comment]
You can try this version - it works on PTR: https://github.com/Backupiseasy/ThreatPlates/releases/tag/11.0.0-alpha1
I did not yet do a lot of testing though.

**Comment by Ravenwylde** [comment]
I will test it for you. happily. Thanks! I'll report back.

**Comment by Ravenwylde** [comment]
LUA error on logging in:

Message: Interface/AddOns/TidyPlates_ThreatPlates/Core.lua:312: attempt to index field '?' (a nil value)
Time: Wed Sep 28 10:06:05 2022
Count: 1
Stack: Interface/AddOns/TidyPlates_ThreatPlates/Core.lua:312: attempt to index field '?' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Core.lua"]:312: in function `CheckForFirstStartUp'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Core.lua"]:422: in function <Interface/AddOns/TidyPlates_ThreatPlates/Core.lua:421>
[string "=[C]"]: ?
[string "@Interface/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:70: in function <...ce/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:65>
[string "@Interface/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:630: in function <...ce/AddOns/Details/Libs/AceAddon-3.0/AceAddon-3.0.lua:615>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:527: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:740: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:102: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:95: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:90: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:82: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:78>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:56: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:59: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:31: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:26>

Locals: <none>

**Comment by Ravenwylde** [comment]
LUA Error when trying to access the app, and when screens load.

Message: ...es/Libs/AceGUI-3.0/widgets/AceGUIContainer-Frame.lua:193: attempt to call method 'SetMinResize' (a nil value)
Time: Wed Sep 28 10:09:32 2022
Count: 1
Stack: ...es/Libs/AceGUI-3.0/widgets/AceGUIContainer-Frame.lua:193: attempt to call method 'SetMinResize' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Libs/AceGUI-3.0/widgets/AceGUIContainer-Frame.lua"]:193: in function `?'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:108: in function <...dyPlates_ThreatPlates/Libs/AceGUI-3.0/AceGUI-3.0.lua:97>
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:146: in function `Create'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1916: in function `Open'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Options.lua"]:10357: in function `OpenOptions'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Options.lua"]:10280: in function <Interface/AddOns/TidyPlates_ThreatPlates/Options.lua:10279>
[string "=[C]"]: ?
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:51: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:49>
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Libs/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:847: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:668>
[string "=[C]"]: ?
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:72: in function <...dyPlates_ThreatPlates/Libs/AceGUI-3.0/AceGUI-3.0.lua:70>
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:306: in function `Fire'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Libs/AceGUI-3.0/widgets/AceGUIWidget-Icon.lua"]:26: in function <...Plates/Libs/AceGUI-3.0/widgets/AceGUIWidget-Icon.lua:25>

Locals: <none>

**Comment by Backupiseasy** [comment]
Do you have Ace3 installed seperately (or from another addon) or are you using the embedded one?

**Comment by Ravenwylde** [comment]
Embedded

**Comment by Backupiseasy** [comment]
For the time being, you could install the most recent alpha version of Ace3 (see https://www.wowace.com/projects/ace3/files).  Once installed, it will be used instead of the embedded one. Ace3 is still work in progress for DF, so - I guess - something like this is to be expected.

**Comment by Ravenwylde** [comment]
Installed that from the link you provided. Getting the following LUA error now.

Message: Interface/AddOns/TidyPlates_ThreatPlates/Core.lua:312: attempt to index field '?' (a nil value)
Time: Thu Sep 29 18:37:19 2022
Count: 1
Stack: Interface/AddOns/TidyPlates_ThreatPlates/Core.lua:312: attempt to index field '?' (a nil value)
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Core.lua"]:312: in function `CheckForFirstStartUp'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Core.lua"]:422: in function <Interface/AddOns/TidyPlates_ThreatPlates/Core.lua:421>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:530: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:739: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:102: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:95: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:90: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:82: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:78>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:56: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:59: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:31: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:26>

Locals: <none>

**Comment by Backupiseasy** [comment]
I just tested it. It's working fine on the PTR, so not sure what is causing this on the beta.

**Comment by Axejess** [comment]
Getting these error myself with the alpha2 and latest ace3: 

Message: ...nterface/AddOns/TidyPlates_ThreatPlates/Database.lua:572: attempt to get length of local 'keys' (a boolean value)
Time: Sat Oct  1 12:25:59 2022
Count: 1
Stack: ...nterface/AddOns/TidyPlates_ThreatPlates/Database.lua:572: attempt to get length of local 'keys' (a boolean value)
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Database.lua"]:572: in function <...nterface/AddOns/TidyPlates_ThreatPlates/Database.lua:571>
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Database.lua"]:1210: in function `Function'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Database.lua"]:1458: in function <...nterface/AddOns/TidyPlates_ThreatPlates/Database.lua:1436>
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Database.lua"]:1481: in function `MigrateDatabase'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Addon.lua"]:226: in function `CheckForFirstStartUp'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Addon.lua"]:369: in function <Interface/AddOns/TidyPlates_ThreatPlates/Addon.lua:313>
[string "=[C]"]: ?
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:70: in function <...ates_ThreatPlates/Libs/AceAddon-3.0/AceAddon-3.0.lua:65>
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:498: in function `InitializeAddon'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:623: in function <...ates_ThreatPlates/Libs/AceAddon-3.0/AceAddon-3.0.lua:615>

Locals: <none>

**Comment by Backupiseasy** [comment]
I uploaded a new version for Dragonflight that at least should work on the PTR, not sure if it will work on Beta as well as I cannot test that. The new version is available here: https://github.com/Backupiseasy/ThreatPlates/releases/tag/11.0.0-alpha3

**Comment by Ravenwylde** [comment]
I can test it and let you know. Thank you!
