### ISSUE TITLE
Dragonflight Beta Support

### ISSUE THREAD

**Issue by Voxxel** [Backupiseasy/ThreatPlates#354]
While ThreatPlates looks mostly working in DF Beta it has an annoying LUA error, continuously popped up in every second as long as any mob (with threat plate) is displayed on the screen. When I turned to a wall, the error counting is halted.

```
101x ...dOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua:2051: attempt to call upvalue 'ShouldSkipAuraUpdate' (a nil value)
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua"]:2051: in function <...dOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua:2030>

Locals:
```

**Comment by Backupiseasy** [comment]
You are using the Retail version for Dragonflight, right? There is a Dragonflight version (see  https://github.com/Backupiseasy/ThreatPlates/releases/tag/11.0.0-alpha2) , but it also has bugs. I'll try to update an updated version.

**Comment by Backupiseasy** [comment]
I uploaded a new version for Dragonflight that at least should work on the PTR, not sure if it will work on Beta as well as I cannot test that. The new version is available here: https://github.com/Backupiseasy/ThreatPlates/releases/tag/11.0.0-alpha3

**Comment by Voxxel** [comment]
Thank you very much for your work, m8!
