### ISSUE TITLE
Nameplates disappears after using Mind Control in PvP

### ISSUE THREAD

**Issue by darvader** [Backupiseasy/ThreatPlates#364]
Steps to repeat:
* use priests Mind Control on an enemy
* after that the nameplate is invisible and 

I got this stack traces:

Message: ...dOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua:1463: attempt to index local 'unit_aura_info' (a nil value)
Time: Sat Nov 12 14:34:33 2022
Count: 8
Stack: ...dOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua:1463: attempt to index local 'unit_aura_info' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua"]:1463: in function <...dOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua:1445>
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua"]:1966: in function `UpdateUnitAuras'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua"]:2192: in function `UpdateAurasGrids'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua"]:2248: in function `UpdateAuras'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua"]:2957: in function `OnUnitAdded'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Widgets/WidgetHandler.lua"]:391: in function `OnUnitAdded'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:360: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:346>
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:400: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:376>
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:467: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:445>
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1127: in function `?'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1081: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1080>

Locals: 

and this:

Message: ...dOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua:1463: attempt to index local 'unit_aura_info' (a nil value)
Time: Sat Nov 12 14:34:40 2022
Count: 773
Stack: ...dOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua:1463: attempt to index local 'unit_aura_info' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua"]:1463: in function <...dOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua:1445>
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua"]:1966: in function `UpdateUnitAuras'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua"]:2192: in function `UpdateAurasGrids'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua"]:2248: in function `UpdateAuras'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua"]:1524: in function <...dOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua:1520>

Locals:

**Comment by darvader** [comment]
Putting an if around it, solves the problem:

if unit_aura_info then
          aura.auraInstanceID = unit_aura_info.auraInstanceID
          aura.UnitAuraInfo = unit_aura_info
          
          unit_auras[#unit_auras + 1] = aura
        end

**Comment by Backupiseasy** [comment]
I really need to fix aura processing soon. There were lot's of changes with 10.0 and it still is really buggy. But a Lua error obviously is something different. Still working on Evoker support, so it might take a few days.

**Comment by Backupiseasy** [comment]
I now verified this bug and will fix it as you suggested above in the upcoming 11.1.0 release. I am still not sure why GetAuraDataBySlot would return a nil value there (although it's possible for the return value to be nil). Although the above fixes the Lua error, I would feel better if I knew why it is nil in this situation happens ...
