### ISSUE TITLE
Party 1 2 3 numbers for nameplates for arena?

### ISSUE THREAD

**Issue by jessicachon** [Backupiseasy/ThreatPlates#370]
Hello I was wondering if threat plates can number party plates in arena just like you can with arena 1 2 3 and have cool things like orbs and also the ability to position those numbers? It would be really helpful to keep track of my players for me! But thank you for making such a awesome addon.

another cool thing to implement would be the ability to change enemy arena name plate colors separate from party, so for instance they could be the darker/lighter version of all the class colors so its easier to read on the battlefield who is the enemy and who is friend.

**Comment by Backupiseasy** [comment]
The following version should now work in solo shuffle: https://drive.google.com/file/d/1JDF23Gr_m8eWZswBvrwMW61gC6m8_N2U/view?usp=sharing

Any feedback is appreciated :)

**Comment by Backupiseasy** [comment]
This issue is now fixed with release 11.1.8.
