### ISSUE TITLE
Debug line left alive in commit for 11.1.5

### ISSUE THREAD

**Issue by gdwiz** [Backupiseasy/ThreatPlates#372]
7f2dffa2e718bf16eed9986fdb6504e2cf702014 uncommented a debug line: https://github.com/Backupiseasy/ThreatPlates/blame/master/Widgets/AurasWidget.lua#L1478

This spams the game console with aura debug messages.

Workaround - modify `Widgets/AurasWidget.lua` locally to recomment the line or delete it.

**Comment by 10leej** [comment]
opened a PR to fix this

**Comment by Backupiseasy** [comment]
Ah, yeah. I'll remove this. The PR reverts everything, not just the debug line. Thanks for reporting this.
