### ISSUE TITLE
Weird Issue with DK Rune Times on Classic

### ISSUE THREAD

**Issue by Gogo1951** [Backupiseasy/ThreatPlates#374]
... when you are dead.

![image](https://user-images.githubusercontent.com/55365231/209622015-f875540d-f72c-4267-b6e4-9b9aa536f952.png)

**Comment by Backupiseasy** [comment]
I am not yet able to reproduce this bug, but I think I know why it could be happening. If so, the following version should fix this issue: https://drive.google.com/file/d/1zUZUB2V9KcJvMqFX1fF-HZyIxnhUdQT6/view?usp=sharing

**Comment by Backupiseasy** [comment]
Fixed in release 11.1.8
