### ISSUE TITLE
Show Friendly won't stick

### ISSUE THREAD

**Issue by Spydawg** [Backupiseasy/ThreatPlates#376]
I always have to enable show friendly Shift-V on log in or after a /RL

I have enabled all the option in settings to have it on (That I could find)  but after a /rl or Log in it's not showing
and I need to Shift-V to turn it on..

**Comment by Backupiseasy** [comment]
Can you test if the same happens with Threat Plates disabled? There is no functionality in Threat Plates that would reset which nameplates are shown/hidden after login, so I have no idea why TP should do that. There are other addons that do that though. So it makes sense to test that first.

**Comment by Spydawg** [comment]
You are right, its another addon.
I just need to figure out the one doing it.. =)
Sorry

**Comment by Backupiseasy** [comment]
No problem, just happy that it was not related to TP :)
