### ISSUE TITLE
Issue with Wrath Classic

### ISSUE THREAD

**Issue by Gogo1951** [Backupiseasy/ThreatPlates#379]
Latest on Curseforge

30x ...idyPlates_ThreatPlates\Widgets\ComboPointsWidget.lua:401: attempt to index field 'Time' (a nil value)
[string "@Interface\AddOns\TidyPlates_ThreatPlates\Widgets\ComboPointsWidget.lua"]:401: in function <...idyPlates_ThreatPlates\Widgets\ComboPointsWidget.lua:385>

Locals:
Skipped (In Encounter)

**Comment by Backupiseasy** [comment]
Ah, that's because of a typo. Will fix it and release a new version. Thanks for reporting it.

**Comment by Backupiseasy** [comment]
Fixed in the newest releasae 11.1.9
