### ISSUE TITLE
Max Distance and Max Distance Behind Camera broken

### ISSUE THREAD

**Issue by kirkwor** [Backupiseasy/ThreatPlates#380]
Couldn't find a duplicate, I can't seem to make the option TP > Blizzard Settings > "Max Distance/Max Distance Behind Camera" using the latest version. This was working fine before Dragonflight.

**Comment by Backupiseasy** [comment]
See my comments here: https://www.curseforge.com/wow/addons/tidy-plates-threat-plates?comment=6791

You should see the same behavior without Threat Plates enabled by, e.g., changing the CVars with chat commands or AdvancedInterfaceOptions. The setttings in the TP options also only change these CVars. So, it seems, that this settings are currently broken in WoW itself. 

I did not find any report of this in the WoW forums though, only old ones.

**Comment by kirkwor** [comment]
Ah, that makes sense, thank you for the quick reply, I will try to see if WoW forums can get it fixed first! :D
