### ISSUE TITLE
Bug: Mouseover Highlight issue

### ISSUE THREAD

**Issue by nancikennedy** [Backupiseasy/ThreatPlates#443]
196x ...yPlates_ThreatPlates/Elements/MouseoverHighlight.lua:38: Usage: UnitIsUnit("unit", "otherUnit")
[string "=[C]"]: ?
[string "@TidyPlates_ThreatPlates/Elements/MouseoverHighlight.lua"]:38: in function <...yPlates_ThreatPlates/Elements/MouseoverHighlight.lua:36>
[string "@TidyPlates_ThreatPlates/Elements/MouseoverHighlight.lua"]:119: in function <...yPlates_ThreatPlates/Elements/MouseoverHighlight.lua:119>

Locals:
(*temporary) = "mouseover"
(*temporary) = nil

**Comment by Backupiseasy** [comment]
https://github.com/Backupiseasy/ThreatPlates/releases/tag/11.1.18-beta2 should fix this

Do you have any additional information when this happend? I guess it should be something like a unit dying/getting its nameplate removed while you mouseovered it. But I am not sure.

**Comment by Backupiseasy** [comment]
The following version should fix this issue: https://drive.google.com/file/d/1m8Hc7VHhnLcqlhWlkjnQifwcD3GuviG8/view?usp=sharing
