### ISSUE TITLE
Allow plate to reveal blizzard "timers" on applicable NPCs

### ISSUE THREAD

**Issue by StarshineWindlord** [Backupiseasy/ThreatPlates#449]
Some NPCs have a special trait that is a timer bar, examples include dockmaster for the dragon isles (your boat will arrive soon) and envoys at the Forgotten Reach (your new quest from this NPC will be available in X hours).   It might also be present on "bunny" markers such as tuskarr fishing nets.

Right now I don't know any way to reveal this timer at the plate if I put one on.

I'm also a little stumped how to identify a single unit to let its blizzard nameplate happen instead, in order to continue to see such timers.

Either a general checkmark to have "timer" plates active their own way, or to reveal the element as if it's an extra bar (and placeable up/down in relation to the plate anchor) would be fine.

**Comment by Backupiseasy** [comment]
Yeah, that's something I am working on for 11.2, but it's a bit complicated, so I am not sure if I will succeed. This should be the same as these requests here: https://github.com/Backupiseasy/ThreatPlates/issues/420.

**Comment by StarshineWindlord** [comment]
I would be willing to rename #449 "Allow Blizz plates forced for identified
units" to distinguish it from "make timer bars happen for timer-aligned
units" that #420 and its kindred cover.

Agreed the example I gave and my inspiration for the ask is the same as 420.

Blizz plate pass through might also address weird NPCs that blizz comes up
with in the future.

**Comment by Backupiseasy** [comment]
I will keep that in mind when working on #420 or this. 

What you mean is that TP as disabled and Blizz plates are enabled when TP detects such a unit (with such a widget), right? That should indeed be possible as a workaround / simple solution.

**Comment by StarshineWindlord** [comment]
Yes, that would be a reasonable workaround.   We'd see the name as we
approach then once in range for a Nameplate we'd see their timers pop
instead.

I don't know if any of the applicable units change nature from not-having
to having one, if so, some sort of recognition for the state change might
be needed.   But so many people seem to need it I'm sure we'd be happy to
test.

**Comment by Emmaleah** [comment]
This is an issue again with the addition of Dream Energy and the NPC Elianna in the Emerald Dream. I really hate having to disable this addon for everything just to see that bar.

**Comment by StarshineWindlord** [comment]
while I found a Weakaura that covers her condition specifically, i agree,
the Blizz folk seem to be using such timers more often now.

It also applies to event portals in some cases, though the diablo crossover
isn't around anymore to test against.

**Comment by Backupiseasy** [comment]
These timers should now be shown since version 11.2.0
