### ISSUE TITLE
no nameplates in pvp

### ISSUE THREAD

**Issue by Ssesmar** [Backupiseasy/ThreatPlates#450]
didnt show any nameplate in pvp

**Comment by Backupiseasy** [comment]
Currently, these seems to be a general WoW problem, not related to Threat Plates: https://us.forums.blizzard.com/en/wow/t/enemy-player-nameplates-not-showing/1579528/13

Once possible fix seems to be to update nameplate max distance with

`/run SetCVar(“nameplatePlayerMaxDistance”, 60)`

or

`/run SetCVar(“nameplateMaxDistance”, 60)`

It does not seem to work in all cases though.

**Comment by Ssesmar** [comment]
it works now as i typed i
/run SetCVar("nameplatePlayerMaxDistance", 60)
