### ISSUE TITLE
Friendly player nameplate is not showing in headline view.

### ISSUE THREAD

**Issue by riass** [Backupiseasy/ThreatPlates#451]
It was like this before the patch as well, 

Everything is showing except the friendly (or enemy) player nameplates in headline view. It only appears on the units I currently target. It should show on all friendly player if headline view mode is active.
Maybe I miss some CVAR options or something, but seemingly everything is on. 

GIF below. 
[here ](https://gyazo.com/2c011e917e8a6f68e7759f081ae01a0b)

Any solution?

**Comment by Backupiseasy** [comment]
Unless it's not something similar than this here #450, you can try the following to see if it's a bug:

- Disable Threat Plates and see if the same happens with WoW default nameplates, i.e., player nameplates only showing when targeted
- With TP enabled, create a new profile with default settings. If it is gone, the issue was settings releated (e.g., setting player transparency to 100% or something else).

**Comment by riass** [comment]
> Unless it's not something similar than this here #450, you can try the following to see if it's a bug:
> 
> * Disable Threat Plates and see if the same happens with WoW default nameplates, i.e., player nameplates only showing when targeted
> * With TP enabled, create a new profile with default settings. If it is gone, the issue was settings releated (e.g., setting player transparency to 100% or something else).

- I see Blizzard default nameplates on friendly showing no matter if TP is enabled or disabled.
- Zero changes when I create new profile, I have already tried that :(

**Comment by neuvo123** [comment]
same issue here except healthbar view not showing friendly targets nameplate till they are targeted

started happen after latest update

**Comment by neuvo123** [comment]
it is some blizz related bug, you have to manually type /run SetCVar(“nameplatePlayerMaxDistance”, 60) on each of your characters

for some reason it doesnt work if you copy paste it, after manually type this on each char i can see friendly and enemy nameplate again

**Comment by riass** [comment]
The above mentioned manually typing method works as funny as it sounds.

Do you know perhaps a run command for Alliance players too? I have warmode off, and I don't see their name as Horde faction player's.

Also @Backupiseasy Do we have an option for status text e.g. guild name only showing in headline view when targeted?

**Comment by neuvo123** [comment]
https://ibb.co/qYwQPg4 i found this why it doesnt work when copy pasted from forums

but I used that code and it fixed for me except now im seeing npcs through floors and walls https://ibb.co/m0GwsLj

I couldnt get neutral npc nameplates disabled from blizzard or addons settings either, after i used that code no matter what i try i see nat pagle through arenas floor

I end up do full cvar reset with advancedinterface options and im not waiting blizzard to fix this as I dont want to see neutral npc's nameplates through arenas floor

**Comment by neuvo123** [comment]
blizzard has fixed the issue and bug were on blizzards end

**Comment by Backupiseasy** [comment]
Good to hear. Thanks for your update on this.
