### ISSUE TITLE
Not sure if TP error

### ISSUE THREAD

**Issue by JH0Ni-github** [Backupiseasy/ThreatPlates#453]
103725x ...eBlizzard_NamePlates/Blizzard_NamePlates.lua:653: calling 'GetParent' on bad self (Usage: local parent = self:GetParent())
[string "=[C]"]: in function `GetParent'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:653: in function `UpdateAnchor'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:758: in function `UpdateBuffs'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:253: in function `OnUnitAuraUpdate'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:145: in function `OnNamePlateAdded'
[string "@Blizzard_NamePlates/Blizzard_NamePlates.lua"]:78: in function <...eBlizzard_NamePlates/Blizzard_NamePlates.lua:69>

Locals:
(*temporary) = Frame {
 IsLayoutFrame = <function> defined @SharedXML/LayoutFrame.lua:36
 GetPadding = <function> defined @SharedXML/LayoutFrame.lua:133
 GetBaseYOffset = <function> defined @Blizzard_NamePlates/Blizzard_NamePlates.lua:648
 SetTargetYOffset = <function> defined @Blizzard_NamePlates/Blizzard_NamePlates.lua:636
 MarkDirty = <function> defined @SharedXML/LayoutFrame.lua:99
 auras = <table> {
 }
 GetChildPadding = <function> defined @SharedXML/LayoutFrame.lua:142
 OnCleaned = <function> defined @SharedXML/LayoutFrame.lua:123
 OnUpdate = <function> defined @SharedXML/LayoutFrame.lua:93
 GetAdditionalRegions = <function> defined @SharedXML/LayoutFrame.lua:85
 GetTargetYOffset = <function> defined @Blizzard_NamePlates/Blizzard_NamePlates.lua:640
 OnShow = <function> defined @SharedXML/LayoutFrame.lua:32
 UpdateAnchor = <function> defined @Blizzard_NamePlates/Blizzard_NamePlates.lua:652
 LayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:272
 dirty = false
 SetActive = <function> defined @Blizzard_NamePlates/Blizzard_NamePlates.lua:670
 SetBaseYOffset = <function> defined @Blizzard_NamePlates/Blizzard_NamePlates.lua:644
 ShouldShowBuff = <function> defined @Blizzard_NamePlates/Blizzard_NamePlates.lua:662
 targetYOffset = 0
 CalculateFrameSize = <function> defined @SharedXML/LayoutFrame.lua:157
 AddLayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:55
 spacing = 4
 HasActiveBuff = <function> defined @Blizzard_NamePlates/Blizzard_NamePlates.lua:694
 GetLayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:73
 fixedHeight = 14
 unit = "nameplate1"
 IsDirty = <function> defined @SharedXML/LayoutFrame.lua:119
 ParseAllAuras = <function> defined @Blizzard_NamePlates/Blizzard_NamePlates.lua:674
 isActive = true
 Layout = <function> defined @SharedXML/LayoutFrame.lua:179
 UpdateBuffs = <function> defined @Blizzard_NamePlates/Blizzard_NamePlates.lua:702
 OnEvent = <function> defined @Blizzard_NamePlates/Blizzard_NamePlates.lua:630
 buffPool = <table> {
 }
 baseYOffset = -3
 0 = <userdata>
 filter = ""
 MarkIgnoreInLayout = <function> defined @SharedXML/LayoutFrame.lua:44
 MarkClean = <function> defined @SharedXML/LayoutFrame.lua:114
 OnLoad = <function> defined @Blizzard_NamePlates/Blizzard_NamePlates.lua:623
 IgnoreLayoutIndex = <function> defined @SharedXML/LayoutFrame.lua:40
}

**Comment by Backupiseasy** [comment]
That does not look like an error from Threat Plates as it is not mentioned in the error message. Is that the first of all the Lua errors you get? In what situation did that happen?
