### ISSUE TITLE
10.1.5 issue – personal resource display not updating

### ISSUE THREAD

**Issue by JeeveStobs** [Backupiseasy/ThreatPlates#462]
This one is very hard to document, as there are no Lua errors thrown, but I can confirm the issue only happens when the Threat Plates add-on is enabled.

Example: when taking damage, the personal resource display (HP/mana bars under character) do not update. It will remain at full health despite taking damage.

Is there any way to turn on additional debugging to capture an error message? Sometimes I see "Interface action failed because of an AddOn" when I start attacking, but doesn't help troubleshoot in any way.

**Comment by Backupiseasy** [comment]
I did not notice that specifically as I don't use the personal nameplate, but I will test. I noticed though that Blizzard healthbars do not get updated if enabled for, e.g., enemy nameplates while TP is active. I guess it's the same bug.

**Comment by Wurger-god** [comment]
Same here for me +++
Happened after a new patch. HP bar (the one that is directly below ur character) is breaking and stops reacting at some point if addon is on :(
Happened for my friend also

**Comment by Wurger-god** [comment]
Seems to be fixed after they uploaded new small patch, maybe not for everyone im not sure

**Comment by class2u** [comment]
It fixed for me! Thank you for the info.

**Comment by Backupiseasy** [comment]
There was one thing that was hotfixed: "Fixed a bug causing displayed health to not update and match actual health values."

I am not sure if this fixed all issues, I still need to test - yesterday I still had a bug with healthbar updates.
