### ISSUE TITLE
LuA error SetFont

### ISSUE THREAD

**Issue by Poisonenvy2** [Backupiseasy/ThreatPlates#464]
Getting this error when I login:

40x ...ceTidyPlates_ThreatPlates/Elements/Fonts.lua:102: bad argument #3 to 'SetFont' (Usage: self:SetFont(fontFile, height, flags))
[string "=[C]"]: in function `SetFont'
[string "@TidyPlates_ThreatPlates/Elements/Fonts.lua"]:102: in function <...ceTidyPlates_ThreatPlates/Elements/Fonts.lua:100>
[string "@TidyPlates_ThreatPlates/Elements/Fonts.lua"]:117: in function `SetNamesFonts'
[string "@TidyPlates_ThreatPlates/Core.lua"]:559: in function `?'
[string "@DataStore/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@DataStore/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@DataStore/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@DataStore/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(*temporary) = SystemFont_NamePlate {
 0 = <userdata>
}
(*temporary) = "Interface\Addons\TidyPlates_ThreatPlates\Fonts\Cabin.ttf"
(*temporary) = 13
(*temporary) = "NONE"

First and only error in bugsack.  Checked version and it's the current one: 11.1.24

**Comment by Backupiseasy** [comment]
It seems that "NONE" is no longer accepted as flags parameter here. It must be an empty string "". I seems to be like that since Dragonflight, but was not enforced or at least NONE did work until 10.1.5, I guess.

Thanks for reporting this. Will fix it as fast as possible.

**Comment by Backupiseasy** [comment]
As a quick fix, it should work to just enable OUTLINE in General - Blizzard Settings - Names.

**Comment by Poisonenvy2** [comment]
Yup .. that worked, thank you.  I did try fiddling with the various font settings, because I guessed it might be "fixable" that way, but I was basically just stabbing at stuff blindly lol

**Comment by Backupiseasy** [comment]
The weird thing is that it only throws a Lua error for the Blizzard nameplate font. All other fonts, e.g., name, health, ..., work fine with "NONE" ...

**Comment by Backupiseasy** [comment]
Fixed in version 11.1.25
