### ISSUE TITLE
Wotlk Classic - Wrong Tooltip Info on Enemy Crowd Control

### ISSUE THREAD

**Issue by B2SquareOne** [Backupiseasy/ThreatPlates#470]
If you activate "Show Crowd Control" for Enemy Unit's and got tooltips for auras also activated you will get false tooltip Infos. 
Like a Piercing Howl will have a Tooltip like any one other buff or debuff the enemey unit has. 

- Widgets - Auras - Crowd Control - Filter - Enemy Unit - Show Crowd Control

**Comment by Backupiseasy** [comment]
So, I could reproduce this issue and fix it - for me at least. Can you verify that this bug is gone with this version: https://drive.google.com/file/d/122XyKbs9BzJ5w-GDYXhfzX4B52QhCYKN/view?usp=sharing

**Comment by Backupiseasy** [comment]
Fixed with release 11.1.26
