### ISSUE TITLE
WOTLK Lua Errors in battlegrounds

### ISSUE THREAD

**Issue by sir-galahad** [Backupiseasy/ThreatPlates#474]
in BGs i was constantly getting the following error (apologies for screenshot instead of text):

![image](https://github.com/Backupiseasy/ThreatPlates/assets/8272140/8c5c5bc2-d7a7-481f-9f0c-24118e0e7ad7)

i found i could current the problem on my local client by modifying `CoreEvents:ARENA_OPPONENT_UPDATE(unitid, update_reason)` to look like the following:

```
function CoreEvents:ARENA_OPPONENT_UPDATE(unitid, update_reason)
  -- my change below
  isArena, _ = IsActiveBattlefieldArena() 
  if isArena ~= true then
    return
  end
  -- my change above
  if update_reason == "seen" and C_PvP.IsSoloShuffle() then
    local plate = PlatesByUnit[unitid]
    if plate then
      plate.UpdateMe = true
      --Addon:ForceUpdateOnNameplate(plate)
    end
  end
end
```

i'm not sure this is the best fix though i don't know if the arena widget should even be loading if not in arena..

**Comment by Backupiseasy** [comment]
C_PvP.IsSoloShuffle() is an API function not available in Wrath Classic; I missed that when fixing a bug some time ago. Thanks for reporting it. I already released a new version 11.1.28 where you should not get this error any longer.
