### ISSUE TITLE
arena number 123 bug after update

### ISSUE THREAD

**Issue by neuvo123** [Backupiseasy/ThreatPlates#486]
Hi, after latest update the setting "Arena Number" doesnt show their number anymore, only red names. I would really like to only see number for them and no names at all, i think something broke on update. So far I have had this in shuffles,skirmish and arenas so the setting doesnt seem to work anymore at all

if you have any idea what might be causing this, thank you alot!

**Comment by Backupiseasy** [comment]
Hm, I think I messed up something. Does the follwing version work for you: https://drive.google.com/file/d/14LagY9FXLoxQjYoPqLbO4kqfPj_i04Nq/view?usp=sharing

**Comment by Wreck5tep** [comment]
Had the same Problem, that version fixed it for me

**Comment by neuvo123** [comment]
thank you i will test it

**Comment by neuvo123** [comment]
> Hm, I think I messed up something. Does the follwing version work for you: https://drive.google.com/file/d/14LagY9FXLoxQjYoPqLbO4kqfPj_i04Nq/view?usp=sharing

im not sure if i was able test this but i replace files in old tptp folder with these and i see only numbers once again even tho the version still reads 11.1.31 in game instead 32, any case it seem to be safe to push update for this if it seem to be fixed with it, thank you!

**Comment by Backupiseasy** [comment]
Fixed with 11.1.32
