### ISSUE TITLE
Abreviation / [] instead of normal characters

### ISSUE THREAD

**Issue by kamabulletone** [Backupiseasy/ThreatPlates#489]
I'm currently plaing on Russian servers and have a problem using abreviation in cyrillic. On the second screen full name looks just fine, but with abreviation instead of normal capital cyrillic chars, comes [] . Is there a way to fix it? 

I tried diffrenet fonts installed in addon, also tried changing fonts in retail/Fonts folder. Nothing seems to work

![image](https://github.com/Backupiseasy/ThreatPlates/assets/70567553/eb02262e-aa4c-476b-91ba-a181eb7cd5b1)
![image](https://github.com/Backupiseasy/ThreatPlates/assets/70567553/402c97ff-a00e-49cd-92b1-12a013f11cd3)

**Comment by Backupiseasy** [comment]
Hm, yeah, I can verify that. Not sure how to solve that though. If I am right, it has something to with Cyrillic characters having two bytes instead of one (sometimes).

**Comment by Backupiseasy** [comment]
So, I think I fixed this issue. Here is a version that should work for you: https://drive.google.com/file/d/1vAuYpc4K6XcPb3cg3VoO3CCCtcE3GJ00/view?usp=sharing

**Comment by kamabulletone** [comment]
Thank you, works good.

**Comment by Backupiseasy** [comment]
Fixed with release 11.1.35
