### ISSUE TITLE
Duck polymorph not being tracked as Crowd Control

### ISSUE THREAD

**Issue by Saxayone** [Backupiseasy/ThreatPlates#499]
Duck polymorph is not being tracked as Crowd Control.
https://www.wowhead.com/spell=391622/polymorph

`  [391622] = LOC_POLYMORPH, -- Polymorph (Duck)`
Should be added to the AurasWidget.lua under CROWD_CONTROL_SPELLS_RETAIL for mages.

Also Mawrat:
`  [321395 = LOC_POLYMORPH, -- Polymorph (Mawrat)`
https://www.wowhead.com/spell=321395/polymorph

**Comment by Backupiseasy** [comment]
Thanks for reporting this. I'll add it to the next release.

**Comment by Backupiseasy** [comment]
The current beta version for 11.1.38 should already show these polymorphs as CC.
