### ISSUE TITLE
"Time Until Arrival" transportation plates don't display

### ISSUE THREAD

**Issue by F-Lambda** [Backupiseasy/ThreatPlates#506]
Special "Time Until Arrival" plates showing when a zeppelin or ship arrives don't display unless you check the "Show Blizzard Nameplates for Friendly Units" option. Examples include the dock and zeppelin masters to head to and from the Dragon Isles.

What it should look like (unselected):
![image](https://github.com/Backupiseasy/ThreatPlates/assets/21232805/797cd81a-b7d9-443e-9da9-fc6c7b0b533d)

What it should look like (selected):
![image](https://github.com/Backupiseasy/ThreatPlates/assets/21232805/22499d4e-6759-4876-a8d9-4973415381ce)

What it looks like instead [no plate at all] (unselected):
![image](https://github.com/Backupiseasy/ThreatPlates/assets/21232805/5b73b271-97ea-46ee-8b6e-3563a440cae8)

Here's the Frame Stack info:
![image](https://github.com/Backupiseasy/ThreatPlates/assets/21232805/35f07f73-8f6e-4fcc-903b-0c97b20dd2df)

**Comment by Backupiseasy** [comment]
It does not work with the current release, yes. In the next release, 11.2, it will work. I just fail to finish it since some months :(
This is the same issue as reported here https://github.com/Backupiseasy/ThreatPlates/issues/420.

**Comment by Backupiseasy** [comment]
The "Time until Arrival" widget should now be shown with TP since release 11.2.0.
