### ISSUE TITLE
Evoker Landslide not being tracked as Crowd Control bug

### ISSUE THREAD

**Issue by Valynor85** [Backupiseasy/ThreatPlates#508]
Hi all,

Evoker's landslide spell is not currently tracked as Crowd Control.
https://www.wowhead.com/spell=358385/landslide

Might be possibile to add it?

Thank you!

**Comment by Backupiseasy** [comment]
See my comment here: https://legacy.curseforge.com/wow/addons/tidy-plates-threat-plates?comment=7241

With release 11.1.42, it should be shown as CC.
