### ISSUE TITLE
[Vanilla] Classic release v11.1.43 broken Libs.xml

### ISSUE THREAD

**Issue by Cheesehyvel** [Backupiseasy/ThreatPlates#510]
On line 30 of Libs.xml in the packaged classic release we have this line:
`<!--@version-bcc@`
It is missing the end of the comment, which breaks the xml and we get a bunch of errors when loading the addon.

Copying line 29-30 from here seems to fix the issue.
https://github.com/Backupiseasy/ThreatPlates/blob/e3df5f688a8ea29d237e8bbfe176d4d476aca330/Libs/Libs.xml#L29

Maybe it has something to do with the packaging of the releases, I don't know.

**Comment by Backupiseasy** [comment]
I deleted one line to much there. Thanks for reporiting this.  I uploaded a new version should fixes this. It should be available in a view minutes.

**Comment by Cheesehyvel** [comment]
Yep, fixed
