### ISSUE TITLE
Errors on cata beta

### ISSUE THREAD

**Issue by tellinz** [Backupiseasy/ThreatPlates#512]
Message: ...ce/AddOns/TidyPlates_ThreatPlates/Elements/Fonts.lua:80: bad argument #1 to 'SetJustifyV' (Usage: self:SetJustifyV(justifyV))
Time: Sun Apr 28 06:59:38 2024
Count: 2022
Stack: ...ce/AddOns/TidyPlates_ThreatPlates/Elements/Fonts.lua:80: bad argument #1 to 'SetJustifyV' (Usage: self:SetJustifyV(justifyV))
[string "=[C]"]: in function `SetJustifyV'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Elements/Fonts.lua"]:80: in function `UpdateTextFont'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Elements/Fonts.lua"]:89: in function `UpdateText'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua"]:2901: in function `UpdateAuraFrame'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua"]:2812: in function `GetAuraFrame'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua"]:2374: in function `UpdateUnitAuras'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua"]:2518: in function `UpdateAurasGrids'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua"]:2573: in function `UpdateAuras'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Widgets/AurasWidget.lua"]:3270: in function `OnUnitAdded'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Widgets/WidgetHandler.lua"]:387: in function `OnUnitAdded'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:591: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:563>
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:651: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:644>
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:389: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:380>

Locals: (*temporary) = FontString {
 0 = <userdata>
}
(*temporary) = "CENTER"

**Comment by Backupiseasy** [comment]
Hm, I actually added a function to migrate these values. I guess that did not yet work.

**Comment by Backupiseasy** [comment]
I uploaded a new version (beta5) that now should migrate all deprectated settings to the correct ones (CENTER => MIDDLE). It will probably take a few minutes until the new versions are visible.

Also, the migration function should be used when updating from beta4 to beta5. If you still get this error, I did something wrong there :(

**Comment by Backupiseasy** [comment]
Beta5 still as an issue with this. The migration function is now there, but it will only be used when loggin in with v11.2.0 and it will not be used when using the new beta5. So, with beta6 I let the migration function run every time when a new release is used for the first time. It should work now.
