### ISSUE TITLE
double plates

### ISSUE THREAD

**Issue by warcraftclassicgamer** [Backupiseasy/ThreatPlates#516]
I am using the latest version of TP for Cataclysm Classic dated May 4, 2024. I see two plates and do not understand why. Otherwise seems to work just fine. Is this an issue on my end or perhaps something else? Attached screenshot for reference.

**Comment by Backupiseasy** [comment]
Hm, I removed some code that prevented that as I thought it would no longer be necessary. I think I was wrong. 

I will add this code again and upload a new version. After that, this issue should be gone.

**Comment by Backupiseasy** [comment]
I just uploaded a new version 11.2.6 that should fix this. I will be available for download in a few minutes.

**Comment by warcraftclassicgamer** [comment]
Thank you for your work and for this addon, you are very much appreciated!
