### ISSUE TITLE
Cata: LUA error in ComboPointsWidget when changing spec with a DK

### ISSUE THREAD

**Issue by maexey** [Backupiseasy/ThreatPlates#518]
Threat plates version: 11.2.8-cata
When changing spec on DK:

1x ...idyPlates_ThreatPlates/Widgets/ComboPointsWidget.lua:781: attempt to call field 'GetSpecialization' (a nil value)
[string "@TidyPlates_ThreatPlates/Widgets/ComboPointsWidget.lua"]:781: in function `?'
[string "@TidyPlates_ThreatPlates/Widgets/WidgetHandler.lua"]:43: in function <...ns/TidyPlates_ThreatPlates/Widgets/WidgetHandler.lua:37>

Locals:
self = <table> {
 UNIT_MAXPOWER = <function> defined @TidyPlates_ThreatPlates/Widgets/ComboPointsWidget.lua:789
 OnTargetUnitAdded = <function> defined @TidyPlates_ThreatPlates/Widgets/ComboPointsWidget.lua:959
 TexCoord = <table> {
 }
 GetThreatPlateForUnit = <function> defined @TidyPlates_ThreatPlates/Widgets/WidgetHandler.lua:203
 UnitPowerMax = 6
 UpdateRunesMainline = <function> defined @TidyPlates_ThreatPlates/Widgets/ComboPointsWidget.lua:520
 UpdateUnitResource = <function> defined @TidyPlates_ThreatPlates/Widgets/ComboPointsWidget.lua:485
 Texture = "Interface\AddOns\TidyPlates_ThreatPlates\Widgets\ComboPointsWidget\ComboPointOrb"
 UpdateComboPointsRogueWithAnimacharge = <function> defined @TidyPlates_ThreatPlates/Widgets/ComboPointsWidget.lua:318
 UPDATE_SHAPESHIFT_FORM = <function> defined @TidyPlates_ThreatPlates/Widgets/ComboPointsWidget.lua:829
 Create = <function> defined @TidyPlates_ThreatPlates/Widgets/ComboPointsWidget.lua:937
 PLAYER_SOFT_ENEMY_CHANGED = <function> defined @TidyPlates_ThreatPlates/Widgets/ComboPointsWidget.lua:809
 DetermineUnitPower = <function> defined @TidyPlates_ThreatPlates/Widgets/ComboPointsWidget.lua:268
 UpdateAllFramesAndNameplateColor = <function> defined @TidyPlates_ThreatPlates/Widgets/WidgetHandler.lua:127
 Colors = <table> {
 }
 ShowInShapeshiftForm = true
 RegistedUnitEvents = <table> {
 }
 GetWidgetFrameForUnit = <function> defined @TidyPlates_ThreatPlates/Widgets/WidgetHandler.lua:211
 TextureCoordinates = <table> {
 }
 UpdateAllFrames = <function> defined @TidyPlates_ThreatPlates/Widgets/WidgetHandler.lua:116
 TargetOnly = true
 UpdateSettings = <function> defined @TidyPlates_ThreatPlates/Widgets/ComboPointsWidget.lua:1128
 EventHandlerFrame = Frame {
 }
 WidgetFrame = Frame {
 }
 TextureOff = "Interface\AddOns\TidyPlates_ThreatPlates\Widgets\ComboPointsWidget\ComboPointOrbOff"
 WidgetHandler = <table> {
 }
 db = <table> {
 }
 RegisterUnitEvent = <function> defined @TidyPlates_ThreatPlates/Widgets/WidgetHandler.lua:74
 PLAYER_TARGET_CHANGED = <function> defined @TidyPlates_ThreatPlates/Widgets/ComboPointsWidget.lua:809
 IconWidth = 13.200000
 OnDisable = <function> defined @TidyPlates_ThreatPlates/Widgets/ComboPointsWidget.lua:902
 PowerType = 5
 UpdateLayout = <function> defined @TidyPlates_ThreatPlates/Widgets/ComboPointsWidget.lua:1090
 UpdateComboPoints = <function> defined @TidyPlates_ThreatPlates/Widgets/ComboPointsWidget.lua:281
 RegisterEvent = <function> defined @TidyPlates_ThreatPlates/Widgets/WidgetHandler.lua:65
 UpdateRunes = <function> defined @TidyPlates_ThreatPlates/Widgets/ComboPointsWidget.lua:485
 OnTargetUnitRemoved = <function> defined @TidyPlates_ThreatPlates/Widgets/ComboPointsWidget.lua:986
 EnabledForStyle = <function> defined @TidyPlates_ThreatPlates/Widgets/ComboPointsWidget.lua:926
 IsEnabled = <function> defined @TidyPlates_ThreatPlates/Widgets/ComboPointsWidget.lua:844
 OnEnable = <function> defined @TidyPlates_ThreatPlates/Widgets/ComboPointsWidget.lua:868
 Name = "ComboPoints"
 IconHeight = 13.200000
 PLAYER_ENTERING_WORLD = <function> defined @TidyPlates_ThreatPlates/Widgets/ComboPointsWidget.lua:821
 UnregisterAllEvents = <function> defined @TidyPlates_ThreatPlates/Widgets/WidgetHandler.lua:100
 UnregisterEvent = <function> defined @TidyPlates_ThreatPlates/Widgets/WidgetHandler.lua:85
 ACTIVE_TALENT_GROUP_CHANGED = <function> defined @TidyPlates_ThreatPlates/Widgets/ComboPointsWidget.lua:778
}
(*temporary) = nil
(*temporary) = "attempt to call field 'GetSpecialization' (a nil value)"
_G = <table> {
 ContainerFrame5Item7 = ContainerFrame5Item7 {
 }

**Comment by Backupiseasy** [comment]
True, that's a wrong change when adding Cata Classic support. I just uploaded a new version 11.2.9 that fixes this bug.

**Comment by maexey** [comment]
thanks you, works like a charm, will close
