### ISSUE TITLE
TWW Beta -GetSpellInfo Errors

### ISSUE THREAD

**Issue by RC-Projects** [Backupiseasy/ThreatPlates#524]
Seeing the following errors on TWW beta on load.

`Message: ...terface/AddOns/TidyPlates_ThreatPlates/Constants.lua:467: attempt to call global 'GetSpellInfo' (a nil value)
Time: Fri Jun  7 22:39:11 2024
Count: 1
Stack: ...terface/AddOns/TidyPlates_ThreatPlates/Constants.lua:467: attempt to call global 'GetSpellInfo' (a nil value)
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Constants.lua"]:467: in function `InitializeTotemInformation'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Constants.lua"]:491: in function `GetDefaultTotemSettings'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Constants.lua"]:1666: in main chunk

Locals: self = <table> {
 IGNORED_STYLES = <table> {
 }
 IS_WRATH_CLASSIC = false
 Cache = <table> {
 }
 Animations = <table> {
 }
 Data = <table> {
 }
 ANCHOR_POINT = <table> {
 }
 CASTBAR_INTERRUPT_HOLD_TIME = 1
 ThreatPlates = <table> {
 }
 ANCHOR_POINT_TEXT = <table> {
 }
 TotemCreatureType = "Totem"
 PlayerName = "Terramagi"
 IS_CLASSIC_SOD = false
 CUSTOM_GLOW_WRAPPER_FUNCTIONS = <table> {
 }
 TOTEMS = <table> {
 }
 IS_TBC_CLASSIC = false
 CUSTOM_GLOW_FUNCTIONS = <table> {
 }
 IS_MAINLINE = true
 MODE_FOR_STYLE = <table> {
 }
 IS_CATA_CLASSIC = false
 ANCHOR_POINT_SETPOINT = <table> {
 }
 AurasFilterMode = <table> {
 }
 CVars = <table> {
 }
 THREAT_VALUE_TYPE = <table> {
 }
 IGNORED_STYLES_WITH_NAMEMODE = <table> {
 }
 TARGET_TEXTURES = <table> {
 }
 PLATE_FADE_IN_TIME = 0.500000
 GLOW_TYPES = <table> {
 }
 DEFAULT_FONT = "Cabin"
 ON_UPDATE_PER_FRAME = 0.008417
 UIScale = 1
 TotemInformation = <table> {
 }
 CUSTOM_PLATES_GLOW_FRAMES = <table> {
 }
 BackdropTemplate = "BackdropTemplate"
 ON_UPDATE_INTERVAL = 0.250000
 Debug = <table> {
 }
 ADDON_DIRECTORY = "Interface\AddOns\TidyPlates_ThreatPlates\"
 DEFAULT_SMALL_FONT = "Arial Narrow"
 IS_CLASSIC = false
 LibUTF8 = <table> {
 }
 PlayerClass = "MAGE"
 WOW_USES_CLASSIC_NAMEPLATES = false
 Logging = <table> {
 }
}
(for state) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
}
(for control) = 1
_ = 1
totem_data = <table> {
 ID = "B1"
 GroupColor = "8b4513"
 Icon = "spell_nature_strengthofearthtotem02"
 SpellID = 2484
}
(*temporary) = nil
(*temporary) = 2484
(*temporary) = "attempt to call global 'GetSpellInfo' (a nil value)"
Addon = <table> {
 IGNORED_STYLES = <table> {
 }
 IS_WRATH_CLASSIC = false
 Cache = <table> {
 }
 Animations = <table> {
 }
 Data = <table> {
 }
 ANCHOR_POINT = <table> {
 }
 CASTBAR_INTERRUPT_HOLD_TIME = 1
 ThreatPlates = <table> {
 }
 ANCHOR_POINT_TEXT = <table> {
 }
 TotemCreatureType = "Totem"
 PlayerName = "Terramagi"
 IS_CLASSIC_SOD = false
 CUSTOM_GLOW_WRAPPER_FUNCTIONS = <table> {
 }
 TOTEMS = <table> {
 }
 IS_TBC_CLASSIC = false
 CUSTOM_GLOW_FUNCTIONS = <table> {
 }
 IS_MAINLINE = true
 MODE_FOR_STYLE = <table> {
 }
 IS_CATA_CLASSIC = false
 ANCHOR_POINT_SETPOINT = <table> {
 }
 AurasFilterMode = <table> {
 }
 CVars = <table> {
 }
 THREAT_VALUE_TYPE = <table> {
 }
 IGNORED_STYLES_WITH_NAMEMODE = <table> {
 }
 TARGET_TEXTURES = <table> {
 }
 PLATE_FADE_IN_TIME = 0.500000
 GLOW_TYPES = <table> {
 }
 DEFAULT_FONT = "Cabin"
 ON_UPDATE_PER_FRAME = 0.008417
 UIScale = 1
 TotemInformation = <table> {
 }
 CUSTOM_PLATES_GLOW_FRAMES = <table> {
 }
 BackdropTemplate = "BackdropTemplate"
 ON_UPDATE_INTERVAL = 0.250000
 Debug = <table> {
 }
 ADDON_DIRECTORY = "Interface\AddOns\TidyPlates_ThreatPlates\"
 DEFAULT_SMALL_FONT = "Arial Narrow"
 IS_CLASSIC = false
 LibUTF8 = <table> {
 }
 PlayerClass = "MAGE"
 WOW_USES_CLASSIC_NAMEPLATES = false
 Logging = <table> {
 }
}
TOTEM_RANKS_CLASSIC = <table> {
 1 = " II"
 2 = " III"
 3 = " IV"
 4 = " V"
 5 = " VI"
 6 = " VII"
 7 = " VIII"
 8 = " IX"
 9 = "`

`Message: Interface/AddOns/TidyPlates_ThreatPlates/Init.lua:264: attempt to call global 'GetAddOnMetadata' (a nil value)
Time: Fri Jun  7 22:39:11 2024
Count: 1
Stack: Interface/AddOns/TidyPlates_ThreatPlates/Init.lua:264: attempt to call global 'GetAddOnMetadata' (a nil value)
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Init.lua"]:264: in function `Meta'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Core.lua"]:220: in main chunk

Locals: value = "title"
meta = nil
(*temporary) = nil
(*temporary) = "TidyPlates_ThreatPlates"
(*temporary) = "title"
(*temporary) = "attempt to call global 'GetAddOnMetadata' (a nil value)"
`

`Message: Interface/AddOns/TidyPlates_ThreatPlates/Init.lua:264: attempt to call global 'GetAddOnMetadata' (a nil value)
Time: Fri Jun  7 22:39:11 2024
Count: 1
Stack: Interface/AddOns/TidyPlates_ThreatPlates/Init.lua:264: attempt to call global 'GetAddOnMetadata' (a nil value)
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Init.lua"]:264: in function `Meta'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Commands.lua"]:8: in main chunk

Locals: value = "version"
meta = nil
(*temporary) = nil
(*temporary) = "TidyPlates_ThreatPlates"
(*temporary) = "version"
(*temporary) = "attempt to call global 'GetAddOnMetadata' (a nil value)"
`

`Message: ...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:2165: attempt to index field 'db' (a nil value)
Time: Fri Jun  7 22:39:12 2024
Count: 2
Stack: ...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:2165: attempt to index field 'db' (a nil value)
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:2165: in function `UIScaleChanged'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1787: in function `?'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1300: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1299>

Locals: self = <table> {
 IS_WRATH_CLASSIC = false
 Theme = <table> {
 }
 TotemCreatureType = "Totem"
 AurasFilterMode = <table> {
 }
 ANCHOR_POINT_SETPOINT = <table> {
 }
 CVars = <table> {
 }
 THREAT_VALUE_TYPE = <table> {
 }
 Font = <table> {
 }
 WOW_USES_CLASSIC_NAMEPLATES = false
 IGNORED_STYLES = <table> {
 }
 LEGACY_CUSTOM_NAMEPLATES = <table> {
 }
 Animations = <table> {
 }
 ThreatPlates = <table> {
 }
 ANCHOR_POINT_TEXT = <table> {
 }
 IS_TBC_CLASSIC = false
 MODE_FOR_STYLE = <table> {
 }
 TotemInformation = <table> {
 }
 ON_UPDATE_PER_FRAME = 0.008417
 CUSTOM_PLATES_GLOW_FRAMES = <table> {
 }
 Debug = <table> {
 }
 PlatesByGUID = <table> {
 }
 EventHandler = <table> {
 }
 LibUTF8 = <table> {
 }
 Logging = <table> {
 }
 PLATE_FADE_IN_TIME = 0.500000
 ANCHOR_POINT = <table> {
 }
 CASTBAR_INTERRUPT_HOLD_TIME = 1
 PlayerName = "Terramagi"
 TOTEMS = <table> {
 }
 SCRIPT_FUNCTIONS = <table> {
 }
 ON_UPDATE_INTERVAL = 0.250000
 IS_CLASSIC = false
 WIDGET_EVENTS = <table> {
 }
 PlatesByUnit = <table> {
 }
 IS_CLASSIC_SOD = false
 Widgets = <table> {
 }
 CUSTOM_GLOW_WRAPPER_FUNCTIONS = <table> {
 }
 Cache = <table> {
 }
 CUSTOM_GLOW_FUNCTIONS = <table> {
 }
 TARGET_TEXTURES = <table> {
 }
 IS_MAINLINE = true
 IS_CATA_CLASSIC = false
 DEFAULT_FONT = "Cabin"
 UIScale = 1
 ADDON_DIRECTORY = "Interface\AddOns\TidyPlates_ThreatPlates\"
 BackdropTemplate = "BackdropTemplate"
 PlatesCreated = <table> {
 }
 DEFAULT_SMALL_FONT = "Arial Narrow"
 GLOW_TYPES = <table> {
 }
 PlayerClass = "MAGE"
 IGNORED_STYLES_WITH_NAMEMODE = <table> {
 }
 PlatesVisible = <table> {
 }
 Data = <table> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'db' (a nil value)"
Addon = <table> {
 IS_WRATH_CLASSIC = false
 Theme = <table> {
 }
 TotemCreatureType = "Totem"
 AurasFilterMode = <table> {
 }
 ANCHOR_POINT_SETPOINT = <table> {
 }
 CVars = <table> {
 }
 THREAT_VALUE_TYPE = <table> {
 }
 Font = <table> {
 }
 WOW_USES_CLASSIC_NAMEPLATES = false
 IGNORED_STYLES = <table> {
 }
 LEGACY_CUSTOM_NAMEPLATES = <table> {
 }
 Animations = <table> {
 }
 ThreatPlates = <table> {
 }
 ANCHOR_POINT_TEXT = <table> {
 }
 IS_TBC_CLASSIC = false
 MODE_FOR_STYLE = <table> {
 }
 TotemInformation = <table> {
 }
 ON_UPDATE_PER_FRAME = 0.008417
 CUSTOM_PLATES_GLOW_FRAMES = <table> {
 }
 Debug = <table> {
 }
 PlatesByGUID = <table> {
 }
 EventHandler = <table> {
 }
 LibUTF8 = <table> {
 }
 Logging = <table> {
 }
 PLATE_FADE_IN_TIME = 0.500000
 ANCHOR_POINT = <table> {
 }
 CASTBAR_INTERRUPT_HOLD_TIME = 1
 PlayerName = "Terramagi"
 TOTEMS = <table> {
 }
 SCRIPT_FUNCTIONS = <table> {
 }
 ON_UPDATE_INTERVAL = 0.250000
 IS_CLASSIC = false
 WIDGET_EVENTS = <table> {
 }
 PlatesByUnit = <table> {
 }
 IS_CLASSIC_SOD = false
 Widgets = <table> {
 }
 CUSTOM_GLOW_WRAPPER_FUNCTIONS = <table> {
 }
 Cache = <table> {
 }
 CUSTOM_GLOW_FUNCTIONS = <table> {
 }
 TARGET_TEXTURES = <table> {
 }
 IS_MAINLINE = true
 IS_CATA_CLASSIC = false
 DEFAULT_FONT = "Cabin"
 UIScale = 1
 ADDON_DIRECTORY = "Interface\AddOns\TidyPlates_ThreatPlates\"
 BackdropTemplate = "BackdropTemplate"
 PlatesCreated = <table> {
 }
 DEFAULT_SMALL_FONT = "Arial Narrow"
 GLOW_TYPES = <table> {
 }
 PlayerClass = "MAGE"
 IGNORED_STYLES_WITH_NAMEMODE = <table> {
 }
 PlatesVisible = <table> {
 }
 Data`

`Message: ...Plates_ThreatPlates/Widgets/TidyPlatesExtensions.lua:39: attempt to index field 'db' (a nil value)
Time: Fri Jun  7 22:40:27 2024
Count: 6
Stack: ...Plates_ThreatPlates/Widgets/TidyPlatesExtensions.lua:39: attempt to index field 'db' (a nil value)
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Widgets/TidyPlatesExtensions.lua"]:39: in function `CreateExtensions'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:554: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:489>
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1345: in function `?'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1300: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1299>

Locals: tp_frame = ThreatPlatesFrameNamePlate6 {
 visual = <table> {
 }
 Parent = NamePlate6 {
 }
 widgets = <table> {
 }
}
visual = <table> {
 customtext = FontString {
 }
 healthbar = StatusBar {
 }
 healthborder = Frame {
 }
 Highlight = Frame {
 }
 threatborder = Frame {
 }
 skullicon = Texture {
 }
 eliteicon = Texture {
 }
 spellicon = Texture {
 }
 level = FontString {
 }
 name = FontString {
 }
 spelltext = FontString {
 }
 textframe = Frame {
 }
 eliteborder = Frame {
 }
 castbar = StatusBar {
 }
 raidicon = Texture {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'db' (a nil value)"
Addon = <table> {
 IS_WRATH_CLASSIC = false
 Theme = <table> {
 }
 TotemCreatureType = "Totem"
 AurasFilterMode = <table> {
 }
 ANCHOR_POINT_SETPOINT = <table> {
 }
 CVars = <table> {
 }
 THREAT_VALUE_TYPE = <table> {
 }
 Font = <table> {
 }
 WOW_USES_CLASSIC_NAMEPLATES = false
 IGNORED_STYLES = <table> {
 }
 LEGACY_CUSTOM_NAMEPLATES = <table> {
 }
 Animations = <table> {
 }
 ThreatPlates = <table> {
 }
 ANCHOR_POINT_TEXT = <table> {
 }
 IS_TBC_CLASSIC = false
 MODE_FOR_STYLE = <table> {
 }
 TotemInformation = <table> {
 }
 ON_UPDATE_PER_FRAME = 0.008417
 CUSTOM_PLATES_GLOW_FRAMES = <table> {
 }
 Debug = <table> {
 }
 PlatesByGUID = <table> {
 }
 EventHandler = <table> {
 }
 LibUTF8 = <table> {
 }
 Logging = <table> {
 }
 PLATE_FADE_IN_TIME = 0.500000
 ANCHOR_POINT = <table> {
 }
 CASTBAR_INTERRUPT_HOLD_TIME = 1
 PlayerName = "Terramagi"
 TOTEMS = <table> {
 }
 SCRIPT_FUNCTIONS = <table> {
 }
 ON_UPDATE_INTERVAL = 0.250000
 IS_CLASSIC = false
 WIDGET_EVENTS = <table> {
 }
 PlatesByUnit = <table> {
 }
 IS_CLASSIC_SOD = false
 Widgets = <table> {
 }
 CUSTOM_GLOW_WRAPPER_FUNCTIONS = <table> {
 }
 Cache = <table> {
 }
 CUSTOM_GLOW_FUNCTIONS = <table> {
 }
 TARGET_TEXTURES = <table> {
 }
 IS_MAINLINE = true
 IS_CATA_CLASSIC = false
 DEFAULT_FONT = "Cabin"
 UIScale = 1
 ADDON_DIRECTORY = "Interface\AddOns\TidyPlates_ThreatPlates\"
 BackdropTemplate = "BackdropTemplate"
 PlatesCreated = <table> {
 }
 DEFAULT_SMALL_FONT = "Arial Narrow"
 GLOW_TYPES = <table> {
 }
 PlayerClass = "MAGE"
 IGNORED_STYLES_WITH_NAMEMODE = <table> {
 }
 PlatesVisible = <table> {
 }
 Data = <table> {
 }
}
ENABLE_ABSORB = false
`

`Message: ...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:784: attempt to index local 'unit' (a nil value)
Time: Fri Jun  7 22:43:00 2024
Count: 7
Stack: ...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:784: attempt to index local 'unit' (a nil value)
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:784: in function `UpdateUnitIdentity'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:647: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:644>
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1376: in function `?'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1300: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1299>

Locals: self = <table> {
 IS_WRATH_CLASSIC = false
 Theme = <table> {
 }
 TotemCreatureType = "Totem"
 AurasFilterMode = <table> {
 }
 ANCHOR_POINT_SETPOINT = <table> {
 }
 CVars = <table> {
 }
 THREAT_VALUE_TYPE = <table> {
 }
 Font = <table> {
 }
 WOW_USES_CLASSIC_NAMEPLATES = false
 IGNORED_STYLES = <table> {
 }
 LEGACY_CUSTOM_NAMEPLATES = <table> {
 }
 Animations = <table> {
 }
 ThreatPlates = <table> {
 }
 ANCHOR_POINT_TEXT = <table> {
 }
 IS_TBC_CLASSIC = false
 MODE_FOR_STYLE = <table> {
 }
 TotemInformation = <table> {
 }
 ON_UPDATE_PER_FRAME = 0.008417
 CUSTOM_PLATES_GLOW_FRAMES = <table> {
 }
 Debug = <table> {
 }
 PlatesByGUID = <table> {
 }
 EventHandler = <table> {
 }
 LibUTF8 = <table> {
 }
 Logging = <table> {
 }
 PLATE_FADE_IN_TIME = 0.500000
 ANCHOR_POINT = <table> {
 }
 CASTBAR_INTERRUPT_HOLD_TIME = 1
 PlayerName = "Terramagi"
 TOTEMS = <table> {
 }
 SCRIPT_FUNCTIONS = <table> {
 }
 ON_UPDATE_INTERVAL = 0.250000
 IS_CLASSIC = false
 WIDGET_EVENTS = <table> {
 }
 PlatesByUnit = <table> {
 }
 IS_CLASSIC_SOD = false
 Widgets = <table> {
 }
 CUSTOM_GLOW_WRAPPER_FUNCTIONS = <table> {
 }
 Cache = <table> {
 }
 CUSTOM_GLOW_FUNCTIONS = <table> {
 }
 TARGET_TEXTURES = <table> {
 }
 IS_MAINLINE = true
 IS_CATA_CLASSIC = false
 DEFAULT_FONT = "Cabin"
 UIScale = 1
 ADDON_DIRECTORY = "Interface\AddOns\TidyPlates_ThreatPlates\"
 BackdropTemplate = "BackdropTemplate"
 PlatesCreated = <table> {
 }
 DEFAULT_SMALL_FONT = "Arial Narrow"
 GLOW_TYPES = <table> {
 }
 PlayerClass = "MAGE"
 IGNORED_STYLES_WITH_NAMEMODE = <table> {
 }
 PlatesVisible = <table> {
 }
 Data = <table> {
 }
}
unit = nil
unitid = "nameplate6"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'unit' (a nil value)"
_G = <table> {
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 HUD_EDIT_MODE_SETTING_ACTION_BAR_HIDE_BAR_ART = "Hide Bar Art"
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 781
 MultiBarLeftActionButton10NormalTexture = MultiBarLeftActionButton10NormalTexture {
 }
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 420
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this community."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 MultiBar7ActionButton5Icon = MultiBar7ActionButton5Icon {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 OPTION_TOOLTIP_SHOW_MULTIBAR4 = "Attached to the left side of Right Action Bar 1 by default"
 LE_GAME_ERR_INVALID_FOLLOW_PVP_COMBAT = 374
 MerchantItem3AltCurrencyFrameItem1Text = MerchantItem3AltCurren`
 
`Message: ...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1399: attempt to index field 'unit' (a nil value)
Time: Fri Jun  7 22:43:06 2024
Count: 2
Stack: ...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1399: attempt to index field 'unit' (a nil value)
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1399: in function `?'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1300: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1299>

Locals: self = "NAME_PLATE_UNIT_REMOVED"
unitid = "nameplate6"
plate = NamePlate6 {
 TPFrame = ThreatPlatesFrameNamePlate6 {
 }
 template = "NamePlateUnitFrameTemplate"
}
frame = ThreatPlatesFrameNamePlate6 {
 visual = <table> {
 }
 Active = false
 Parent = NamePlate6 {
 }
 widgets = <table> {
 }
}
(*temporary) = nil
(*temporary) = ThreatPlatesFrameNamePlate6 {
 visual = <table> {
 }
 Active = false
 Parent = NamePlate6 {
 }
 widgets = <table> {
 }
}
(*temporary) = nil
(*temporary) = "attempt to index field 'unit' (a nil value)"
PlatesVisible = <table> {
}
PlatesByUnit = <table> {
}
PlatesByGUID = <table> {
}
Widgets = <table> {
 RegisteredEventsByWidget = <table> {
 }
 EventHandlerFrame = Frame {
 }
 Widgets = <table> {
 }
 EnabledTargetWidgets = <table> {
 }
 EnabledWidgets = <table> {
 }
}
`

**Comment by RC-Projects** [comment]
Sorry for the formatting, the code tics on GH seemed to conflict with the tics in the code. Let me know if sharing these in a different manner would help.

**Comment by Backupiseasy** [comment]
There is not yet a working version for Threat Plates for TWW beta. I fixed some issues now (like the above one, thanks for posting that here), but probably not all. I'll try to provide a working version in the next days.

**Comment by RC-Projects** [comment]
No worries, thanks!

**Comment by Backupiseasy** [comment]
The following is a basic version that should work in TWW. There are no Lua errors that I know of, but I did not test everything yet. Also, Shaman totems or CC auras are not up to date.

https://drive.google.com/file/d/1lyxmM7Q65ZOPuXr6Q6v_Bd5Zz_xvZDGl/view?usp=sharing

I cannot upload it currently as a beta version as LibCustomGlow does not load in TWW and I do not want to disable it for retail.

**Comment by RC-Projects** [comment]
Thanks soo much for putting the time into updating this, I really appreciate it! I no longer see any errors as well. 

From the beta update today, it looks like they made some more changes to the API as some other addons broke. I'll hold off on chasing any further updates until Blizzard is done making changes. Thanks again!
