### ISSUE TITLE
War within beta errors

### ISSUE THREAD

**Issue by Axejess** [Backupiseasy/ThreatPlates#525]
1:
Message: ...terface/AddOns/TidyPlates_ThreatPlates/Constants.lua:467: attempt to call global 'GetSpellInfo' (a nil value)
Time: Fri Jun 14 13:00:53 2024
Count: 1
Stack: ...terface/AddOns/TidyPlates_ThreatPlates/Constants.lua:467: attempt to call global 'GetSpellInfo' (a nil value)
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Constants.lua"]:467: in function `InitializeTotemInformation'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Constants.lua"]:491: in function `GetDefaultTotemSettings'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Constants.lua"]:1666: in main chunk

Locals: self = <table> {
 IGNORED_STYLES = <table> {
 }
 IS_WRATH_CLASSIC = false
 Cache = <table> {
 }
 Animations = <table> {
 }
 Data = <table> {
 }
 ANCHOR_POINT = <table> {
 }
 CASTBAR_INTERRUPT_HOLD_TIME = 1
 ThreatPlates = <table> {
 }
 ANCHOR_POINT_TEXT = <table> {
 }
 TotemCreatureType = "Totem"
 PlayerName = "Axejess"
 IS_CLASSIC_SOD = false
 CUSTOM_GLOW_WRAPPER_FUNCTIONS = <table> {
 }
 TOTEMS = <table> {
 }
 IS_TBC_CLASSIC = false
 CUSTOM_GLOW_FUNCTIONS = <table> {
 }
 IS_MAINLINE = true
 MODE_FOR_STYLE = <table> {
 }
 IS_CATA_CLASSIC = false
 ANCHOR_POINT_SETPOINT = <table> {
 }
 AurasFilterMode = <table> {
 }
 CVars = <table> {
 }
 THREAT_VALUE_TYPE = <table> {
 }
 IGNORED_STYLES_WITH_NAMEMODE = <table> {
 }
 TARGET_TEXTURES = <table> {
 }
 PLATE_FADE_IN_TIME = 0.500000
 GLOW_TYPES = <table> {
 }
 DEFAULT_FONT = "Cabin"
 ON_UPDATE_PER_FRAME = 0.020083
 UIScale = 1
 TotemInformation = <table> {
 }
 CUSTOM_PLATES_GLOW_FRAMES = <table> {
 }
 BackdropTemplate = "BackdropTemplate"
 ON_UPDATE_INTERVAL = 0.250000
 Debug = <table> {
 }
 ADDON_DIRECTORY = "Interface\AddOns\TidyPlates_ThreatPlates\"
 DEFAULT_SMALL_FONT = "Arial Narrow"
 IS_CLASSIC = false
 LibUTF8 = <table> {
 }
 PlayerClass = "HUNTER"
 WOW_USES_CLASSIC_NAMEPLATES = false
 Logging = <table> {
 }
}
(for state) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
 14 = <table> {
 }
 15 = <table> {
 }
 16 = <table> {
 }
 17 = <table> {
 }
 18 = <table> {
 }
 19 = <table> {
 }
 20 = <table> {
 }
 21 = <table> {
 }
 22 = <table> {
 }
 23 = <table> {
 }
}
(for control) = 1
_ = 1
totem_data = <table> {
 ID = "B1"
 GroupColor = "8b4513"
 Icon = "spell_nature_strengthofearthtotem02"
 SpellID = 2484
}
(*temporary) = nil
(*temporary) = 2484
(*temporary) = "attempt to call global 'GetSpellInfo' (a nil value)"
Addon = <table> {
 IGNORED_STYLES = <table> {
 }
 IS_WRATH_CLASSIC = false
 Cache = <table> {
 }
 Animations = <table> {
 }
 Data = <table> {
 }
 ANCHOR_POINT = <table> {
 }
 CASTBAR_INTERRUPT_HOLD_TIME = 1
 ThreatPlates = <table> {
 }
 ANCHOR_POINT_TEXT = <table> {
 }
 TotemCreatureType = "Totem"
 PlayerName = "Axejess"
 IS_CLASSIC_SOD = false
 CUSTOM_GLOW_WRAPPER_FUNCTIONS = <table> {
 }
 TOTEMS = <table> {
 }
 IS_TBC_CLASSIC = false
 CUSTOM_GLOW_FUNCTIONS = <table> {
 }
 IS_MAINLINE = true
 MODE_FOR_STYLE = <table> {
 }
 IS_CATA_CLASSIC = false
 ANCHOR_POINT_SETPOINT = <table> {
 }
 AurasFilterMode = <table> {
 }
 CVars = <table> {
 }
 THREAT_VALUE_TYPE = <table> {
 }
 IGNORED_STYLES_WITH_NAMEMODE = <table> {
 }
 TARGET_TEXTURES = <table> {
 }
 PLATE_FADE_IN_TIME = 0.500000
 GLOW_TYPES = <table> {
 }
 DEFAULT_FONT = "Cabin"
 ON_UPDATE_PER_FRAME = 0.020083
 UIScale = 1
 TotemInformation = <table> {
 }
 CUSTOM_PLATES_GLOW_FRAMES = <table> {
 }
 BackdropTemplate = "BackdropTemplate"
 ON_UPDATE_INTERVAL = 0.250000
 Debug = <table> {
 }
 ADDON_DIRECTORY = "Interface\AddOns\TidyPlates_ThreatPlates\"
 DEFAULT_SMALL_FONT = "Arial Narrow"
 IS_CLASSIC = false
 LibUTF8 = <table> {
 }
 PlayerClass = "HUNTER"
 WOW_USES_CLASSIC_NAMEPLATES = false
 Logging = <table> {
 }
}
TOTEM_RANKS_CLASSIC = <table> {
 1 = " II"
 2 = " III"
 3 = " IV"
 4 = " V"
 5 = " VI"
 6 = " VII"
 7 = " VIII"
 8 = " IX"
 9 = "

2:
Message: Interface/AddOns/TidyPlates_ThreatPlates/Init.lua:264: attempt to call global 'GetAddOnMetadata' (a nil value)
Time: Fri Jun 14 13:00:53 2024
Count: 1
Stack: Interface/AddOns/TidyPlates_ThreatPlates/Init.lua:264: attempt to call global 'GetAddOnMetadata' (a nil value)
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Init.lua"]:264: in function `Meta'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Core.lua"]:220: in main chunk

Locals: value = "title"
meta = nil
(*temporary) = nil
(*temporary) = "TidyPlates_ThreatPlates"
(*temporary) = "title"
(*temporary) = "attempt to call global 'GetAddOnMetadata' (a nil value)"

3:
Message: Interface/AddOns/TidyPlates_ThreatPlates/Init.lua:264: attempt to call global 'GetAddOnMetadata' (a nil value)
Time: Fri Jun 14 13:00:53 2024
Count: 1
Stack: Interface/AddOns/TidyPlates_ThreatPlates/Init.lua:264: attempt to call global 'GetAddOnMetadata' (a nil value)
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Init.lua"]:264: in function `Meta'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Commands.lua"]:8: in main chunk

Locals: value = "version"
meta = nil
(*temporary) = nil
(*temporary) = "TidyPlates_ThreatPlates"
(*temporary) = "version"
(*temporary) = "attempt to call global 'GetAddOnMetadata' (a nil value)"

4:
Message: ...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:2165: attempt to index field 'db' (a nil value)
Time: Fri Jun 14 13:00:53 2024
Count: 2
Stack: ...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:2165: attempt to index field 'db' (a nil value)
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:2165: in function `UIScaleChanged'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1787: in function `?'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1300: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1299>

Locals: self = <table> {
 IS_WRATH_CLASSIC = false
 Theme = <table> {
 }
 TotemCreatureType = "Totem"
 AurasFilterMode = <table> {
 }
 ANCHOR_POINT_SETPOINT = <table> {
 }
 CVars = <table> {
 }
 THREAT_VALUE_TYPE = <table> {
 }
 Font = <table> {
 }
 WOW_USES_CLASSIC_NAMEPLATES = false
 IGNORED_STYLES = <table> {
 }
 LEGACY_CUSTOM_NAMEPLATES = <table> {
 }
 Animations = <table> {
 }
 ThreatPlates = <table> {
 }
 ANCHOR_POINT_TEXT = <table> {
 }
 IS_TBC_CLASSIC = false
 MODE_FOR_STYLE = <table> {
 }
 TotemInformation = <table> {
 }
 ON_UPDATE_PER_FRAME = 0.020083
 CUSTOM_PLATES_GLOW_FRAMES = <table> {
 }
 Debug = <table> {
 }
 PlatesByGUID = <table> {
 }
 EventHandler = <table> {
 }
 LibUTF8 = <table> {
 }
 Logging = <table> {
 }
 PLATE_FADE_IN_TIME = 0.500000
 ANCHOR_POINT = <table> {
 }
 CASTBAR_INTERRUPT_HOLD_TIME = 1
 PlayerName = "Axejess"
 TOTEMS = <table> {
 }
 SCRIPT_FUNCTIONS = <table> {
 }
 ON_UPDATE_INTERVAL = 0.250000
 IS_CLASSIC = false
 WIDGET_EVENTS = <table> {
 }
 PlatesByUnit = <table> {
 }
 IS_CLASSIC_SOD = false
 Widgets = <table> {
 }
 CUSTOM_GLOW_WRAPPER_FUNCTIONS = <table> {
 }
 Cache = <table> {
 }
 CUSTOM_GLOW_FUNCTIONS = <table> {
 }
 TARGET_TEXTURES = <table> {
 }
 IS_MAINLINE = true
 IS_CATA_CLASSIC = false
 DEFAULT_FONT = "Cabin"
 UIScale = 1
 ADDON_DIRECTORY = "Interface\AddOns\TidyPlates_ThreatPlates\"
 BackdropTemplate = "BackdropTemplate"
 PlatesCreated = <table> {
 }
 DEFAULT_SMALL_FONT = "Arial Narrow"
 GLOW_TYPES = <table> {
 }
 PlayerClass = "HUNTER"
 IGNORED_STYLES_WITH_NAMEMODE = <table> {
 }
 PlatesVisible = <table> {
 }
 Data = <table> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'db' (a nil value)"
Addon = <table> {
 IS_WRATH_CLASSIC = false
 Theme = <table> {
 }
 TotemCreatureType = "Totem"
 AurasFilterMode = <table> {
 }
 ANCHOR_POINT_SETPOINT = <table> {
 }
 CVars = <table> {
 }
 THREAT_VALUE_TYPE = <table> {
 }
 Font = <table> {
 }
 WOW_USES_CLASSIC_NAMEPLATES = false
 IGNORED_STYLES = <table> {
 }
 LEGACY_CUSTOM_NAMEPLATES = <table> {
 }
 Animations = <table> {
 }
 ThreatPlates = <table> {
 }
 ANCHOR_POINT_TEXT = <table> {
 }
 IS_TBC_CLASSIC = false
 MODE_FOR_STYLE = <table> {
 }
 TotemInformation = <table> {
 }
 ON_UPDATE_PER_FRAME = 0.020083
 CUSTOM_PLATES_GLOW_FRAMES = <table> {
 }
 Debug = <table> {
 }
 PlatesByGUID = <table> {
 }
 EventHandler = <table> {
 }
 LibUTF8 = <table> {
 }
 Logging = <table> {
 }
 PLATE_FADE_IN_TIME = 0.500000
 ANCHOR_POINT = <table> {
 }
 CASTBAR_INTERRUPT_HOLD_TIME = 1
 PlayerName = "Axejess"
 TOTEMS = <table> {
 }
 SCRIPT_FUNCTIONS = <table> {
 }
 ON_UPDATE_INTERVAL = 0.250000
 IS_CLASSIC = false
 WIDGET_EVENTS = <table> {
 }
 PlatesByUnit = <table> {
 }
 IS_CLASSIC_SOD = false
 Widgets = <table> {
 }
 CUSTOM_GLOW_WRAPPER_FUNCTIONS = <table> {
 }
 Cache = <table> {
 }
 CUSTOM_GLOW_FUNCTIONS = <table> {
 }
 TARGET_TEXTURES = <table> {
 }
 IS_MAINLINE = true
 IS_CATA_CLASSIC = false
 DEFAULT_FONT = "Cabin"
 UIScale = 1
 ADDON_DIRECTORY = "Interface\AddOns\TidyPlates_ThreatPlates\"
 BackdropTemplate = "BackdropTemplate"
 PlatesCreated = <table> {
 }
 DEFAULT_SMALL_FONT = "Arial Narrow"
 GLOW_TYPES = <table> {
 }
 PlayerClass = "HUNTER"
 IGNORED_STYLES_WITH_NAMEMODE = <table> {
 }
 PlatesVisible = <table> {
 }
 Data

**Comment by Backupiseasy** [comment]
There's a version that should work: https://github.com/Backupiseasy/ThreatPlates/issues/524

I will also upload a new beta version (for 12.0.0) that should work as well in the next days.
