### ISSUE TITLE
Combo point widget disappears

### ISSUE THREAD

**Issue by KyoukanGG** [Backupiseasy/ThreatPlates#528]
Observations

- Sporadically while in combat the combo point widget will disappear from the current target
- Selecting a new target brings the widget back, as well as re-targeting the original target that the widget disappeared on
- Gaining new combo points or spending combo points does not cause the widget to reappear
- Issue began with the most recent update (or at the very least I didn't notice it before the most recent update)
- Does not throw any Lua errors
- Combo points still appear on the target via other addons (e.g. on Shadowed Unit Frames's target frame)

Speculation

- Could be related to rapidly gaining combo points (e.g. when using Fan the Hammer procs as an Outlaw rogue)
- Could be related to a mob dying to Blade Flurry (e.g. while not the primary target)
- I don't believe I've triggered the issue when only in combat with one target, but not certain

EDIT: After some more testing, it feels like killing a secondary target right after switching targets might be the cause, but it's not consistent. Maybe some kind of race condition with events? This seems like the most reliable reproduction steps:

1. Pull multiple targets
2. Focus one target down
3. Swap to a new target right before the focus target dies
4. Kill the first target via indirect damage (e.g. dots, Blade Flurry, etc.)
5. Combo point widget disappears on new target

**Comment by Backupiseasy** [comment]
What version are you currently using? The beta version (for TWW) or the most recent 11.2.x version?

**Comment by KyoukanGG** [comment]
> What version are you currently using? The beta version (for TWW) or the most recent 11.2.x version?

I'm on 11.2.13

**Comment by KyoukanGG** [comment]
Just adding that this occurs with Windwalker as well, same rough reproduction steps. Hopefully this eliminates it being tied to any rogue specific talents/spells/hooks. I assume that it would also occur on Feral, but I haven't made one of those yet... :)

**Comment by KyoukanGG** [comment]
Another update - in TWW early access this occurs basically any time enemies you are in combat with die while not being your current target (e.g. anytime you pull more than one mob at once).

Currently using version 12.0.9

**Comment by Backupiseasy** [comment]
It's really a weird behaviour that I do not experience myself (but I play a druid). I also do not get any other reports regarding this.

**Comment by Backupiseasy** [comment]
The only change I can think of that could cause this is the addition of soft-target support. Do you have soft-targeting enabled (for friendly/enemy/... units)? And if so, what exactly do you have enabled?

**Comment by KyoukanGG** [comment]
I actually had no idea this was a thing, so it's unlikely I've opted into it somehow. Judging by AdvancedInterfaceOptions' CVar browser, I have the soft targeting related settings at default (e.g. only enabled for Gamepad). See attached.

I *do* have SoftTargetInteract set to 3 (BetterFishing made this change to fish with a single keybind), but as far as I can tell that doesn't have anything to do with combat, only interaction with objects.

I also attached a clip of it happening just in case you can spot something I might not know to look for, though this is slightly different than described above. In this clip the widget disappears when the current target dies, and a new target is selected.

![Wow_zkoT5llnL2](https://github.com/user-attachments/assets/7965aef7-ad80-46a7-ada2-96230d556f3a)

https://github.com/user-attachments/assets/4b26dbd4-a221-455f-83c1-59de2fc3c6b8

**Comment by Backupiseasy** [comment]
I still fail to reproduce this, even with a rogue. For me, the CP always correctly reset once a mob dies. Can you test if this also happens with all other addons disabled (if you did not yet do that)?

**Comment by Backupiseasy** [comment]
I just noticed something. After the first mob died, the second mob did get the combo points display, but only for a very short time until it gets hidden again when the first mob finally dies.

![image](https://github.com/user-attachments/assets/491e63a7-665e-476d-86d1-af630cc0df5c)

What I can see is: The first mob dies and your target immediately switches to the second mob. The combo point widget is also shown on the seoncd mob. Then, the first mob switches to headline view as it's dead (which is something I added some time ago). When it finally dies, the nameplate (in headline view) disapears and so does the combo points widget on the second mob.

**Comment by Backupiseasy** [comment]
I think I now know why it happens, but I still need to verify. If I am correct, it should work without bugs when you disable SoftTargetInteract (I think you need to set it to 0). 

Basically, when  a nameplate from a unit is removed, all target-unit-based widgets are hidden. Now, when I added soft-target-support, I also do this for soft-target units, e.g., the first mob, that died, which is a interact target in this second (as can be seen by the loot icon above its nameplate). 

The combo points widget only works for non-soft-target, but the hidding function is called for soft-targets as well. So, I should be able to fix this bug by only process real targets in the hidding function of the combo points widget. 

Puh ....

**Comment by Backupiseasy** [comment]
So, can you test if the bug is fixed in this version: https://drive.google.com/file/d/1XrRMImuWJhKODpRaIVrp45tS84H9y9Yp/view?usp=sharing

**Comment by KyoukanGG** [comment]
I'm not 100% sure this fixes it, because it's a bit inconsistent, but from doing a handful of work quests and intentionally trying to break it by tabbing around a lot while mobs are dying, trying to kill things at the same time, etc. it seems to be resolved.

I'll keep this version installed and will keep an eye on it, and report back regardless of good or bad news when I'm done playing for the day.

**Comment by KyoukanGG** [comment]
Still seems solved, I think that did it! Thanks for taking the time to dig into it!

I'm surprised that this isn't something more people experience, but I guess that the interact key just isn't something most people use. I guess to be fair, I only really use it when fishing as it allows you to fish without looking at the screen or using the mouse.

**Comment by Backupiseasy** [comment]
Actually, the above version will still have bugs when you enable soft-enemy targeting (which you don't have enabled). So, it's more complicated than I thought, but I think I have fixed it now. Still need to look into the resource widget which should have similar issues.

**Comment by Backupiseasy** [comment]
I just uploaded a new beta version that might fix this issue for combo and target widgets. Any feedback if you still see the bug would be appreciated.

**Comment by KyoukanGG** [comment]
I actually haven't seen the bug since installing the version you uploaded to drive; however, I'll swap over to the beta version and give it a go. Will report back if I see any issues.

**Comment by KyoukanGG** [comment]
Handful of dungeons, delves, and world quests, still no issues!

**Comment by KyoukanGG** [comment]
Handful of delves, dungeons, and world quests. Still without issue! Not sure if you want the opener to close the ticket or if you wait until it's merged into release and close yourself, so I'll just leave it for now.

Thanks again!

**Comment by KyoukanGG** [comment]
I'm actually seeing somewhat of a regression, though I'm not sure if it was beta2 or beta3 that introduced it. Rarely when targeting a new enemy with existing combo points, there is no combo point widget. As with the original issue, switching targets returns the widget.

I'm not entirely sure what causes it, but it may have something to do with party members putting me into combat before I target the mob or something? I think I may not have noticed it right after installing the beta versions because I hadn't done any group content until recently, and it seems to only appear while in a group (but I'm not positive).

**Comment by Backupiseasy** [comment]
I found at least one place where the combo points widget is hidden even when you target a unit. But, this only happens when you have soft-target for enemy units enabled. Otherwise, this should not be triggered.

There might be additional bugs like this though. So, I will continue searching. 

Which soft-targets do you have enabled (none, enemy, friend, interact) currently?

**Comment by KyoukanGG** [comment]
Just double checked and my CVars, see below:

![361259988-7965aef7-ad80-46a7-ada2-96230d556f3a](https://github.com/user-attachments/assets/a7bd8ac5-589c-474b-b219-59f8257ef783)

**Comment by Backupiseasy** [comment]
This is hopefully fixed now in version 12.0.10

**Comment by KyoukanGG** [comment]
Just updated, will let you know if I see any issues (or close this out if it seems good to go). I'll likely do some keys tomorrow which is the best place to check this.

**Comment by KyoukanGG** [comment]
Still good to go!
