### ISSUE TITLE
github code vs production code doesnt match

### ISSUE THREAD

**Issue by steijner** [Backupiseasy/ThreatPlates#530]
I have found a few things id like to add a PR for but cloning the repo from here doesnt match the code in the production addon downloaded from curseforge, makes it hard for me to help contribute, or is it something im missing?

Example:
In production addon "CROWD_CONTROL_SPELLS_CATA_CLASSIC" dictionary exists on row 378 in AurasWidget.lua but doesnt exists in the code here on github?

**Comment by Backupiseasy** [comment]
You need to checkout the correct branch. This is a bit complicated, but the correct branch for 11.2.x is devel/112/main: https://github.com/Backupiseasy/ThreatPlates/tree/devel/112/main

It's a bit complicated with all these branches. I want to simplify this, but not yet sure how.

**Comment by Backupiseasy** [comment]
Maybe it's even better to add this to the new 12.0 branch (https://github.com/Backupiseasy/ThreatPlates/tree/devel/120/main, for TWW) as 11.2.x will only have bugfixes, but no new features. So, I would recommend to checkout branch 12.0 and make the PR against this branch.

**Comment by steijner** [comment]
Ah, i missed the different branches, thanks! Added a PR (#531) to the 120 branch :)
