### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by MetalHeadSeven** [Backupiseasy/ThreatPlates#534]
In the latest version 12.0.0-beta3 Debug is on and I don't see a setting to turn it off,  In combat it's all I can see in chat.

**Comment by Backupiseasy** [comment]
Can you post the mesage you see in the chat here?

**Comment by Backupiseasy** [comment]
I think I found it in the Auras widget. Will updated and release a new beta version. Thanks for reporting.

**Comment by MetalHeadSeven** [comment]
Happy to help.  It is Aura's sample included.
![Debug](https://github.com/user-attachments/assets/311a7ead-1a1e-4902-b510-6989a92ec350)
