### ISSUE TITLE
Still seems broken 12.0.4

### ISSUE THREAD

**Issue by rcymbalist** [Backupiseasy/ThreatPlates#546]
Still seems broken after the 12.0.4 update.
- Makes the wow game extremely choppy when turned on.
- the namepates are not even showing
- Cannot even bring up the options UI

**Comment by rcymbalist** [comment]
12.0.5 update- everything seems to be back in working order thank you!!!

**Comment by Backupiseasy** [comment]
Good to hear. There were some changes in the API (deprecated stuff was removed) which I would not thought would happen in such a minor release ...

If you still run across bugs, post them here.
