### ISSUE TITLE
Threatplates not working on retail? /tptp not working

### ISSUE THREAD

**Issue by Solaervrang** [Backupiseasy/ThreatPlates#548]
Hoi.

Have everything enabled, tried towards several chars. Threatplates not working and can't get into config mode?

**Comment by Backupiseasy** [comment]
It works just fine (except some bugs since the latest path). If it's not working, you should get Lua errors. 

Can you open the options dialog with /tptp?

Without any further information, it's hard to tell, but you are the only one currently reporting that it's not working at all for them.

**Comment by Solaervrang** [comment]
Ye, that's what strange. I could not see any other topics on it, i can't open with /tptp

![image](https://github.com/user-attachments/assets/16cadef5-ca2f-4a04-93a7-0b907ad4cd76)

![image](https://github.com/user-attachments/assets/8dbe516c-a15a-4e60-9f04-eb60a364fb4b)

**Comment by Solaervrang** [comment]
1x ...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:979: attempt to index upvalue 'style' (a nil value)
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:979: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:978>
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1045: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1042>
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:628: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:603>
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:672: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:645>
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1381: in function `?'
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1302: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1301>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index upvalue 'style' (a nil value)"
unit = <table> {
 IsSoftEnemyTarget = false
 guid = "Creature-0-4246-2444-5885-216946-00003DC86A"
 isMouseover = false
 IsSoftInteractTarget = false
 IsFocus = false
 IsBossOrRare = true
 level = -1
 red = 0
 levelcolorRed = 0.500000
 IsSoftTarget = false
 unitid = "nameplate6"
 name = "Chromie"
 isElite = true
 levelcolorBlue = 0.500000
 isBoss = true
 healthmax = 15755929
 isTarget = false
 levelcolorGreen = 0.500000
 NPCID = "216946"
 TP_DetailedUnitType = "FriendlyNPC"
 isTapped = false
 classification = "boss"
 blue = 0
 isMarked = false
 isInCombat = false
 IsInterrupted = false
 threatSituation = "LOW"
 threatValue = 0
 IsSoftFriendTarget = false
 class = ""
 reaction = "FRIENDLY"
 green = 1
 health = 15755929
 isRare = false
 type = "NPC"
 isCasting = false
}
style = nil
visual = <table> {
 absorbbar = Texture {
 }
 customtext = FontString {
 }
 healthbar = StatusBar {
 }
 healthborder = Frame {
 }
 Highlight = Frame {
 }
 threatborder = Frame {
 }
 skullicon = Texture {
 }
 eliteicon = Texture {
 }
 spellicon = Texture {
 }
 level = FontString {
 }
 name = FontString {
 }
 spelltext = FontString {
 }
 textframe = Frame {
 }
 eliteborder = Frame {
 }
 castbar = StatusBar {
 }
 raidicon = Texture {
 }
}

**Comment by Solaervrang** [comment]
27x ...Ons/TidyPlates_ThreatPlates/Functions/healthtext.lua:322: attempt to index field 'style' (a nil value)
[string "@TidyPlates_ThreatPlates/Functions/healthtext.lua"]:322: in function `SetCustomText'
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1811: in function `?'
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1302: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1301>

Locals:
tp_frame = ThreatPlatesFrameNamePlate22 {
 WidgetContainer = Frame {
 }
 stylename = ""
 Parent = NamePlate22 {
 }
 unitcache = <table> {
 }
 widgets = <table> {
 }
 IsOccluded = false
 Active = true
 visual = <table> {
 }
 unit = <table> {
 }
}
unit = <table> {
 IsSoftEnemyTarget = false
 guid = "Player-1305-0CCE57DC"
 isMouseover = false
 IsSoftInteractTarget = false
 IsFocus = false
 IsBossOrRare = false
 level = 70
 red = 0
 levelcolorRed = 1
 IsSoftTarget = false
 unitid = "nameplate22"
 name = "Æðøðæ"
 isElite = false
 levelcolorBlue = 0
 isBoss = false
 healthmax = 1604526
 isTarget = false
 levelcolorGreen = 0.820000
 TP_DetailedUnitType = "FriendlyPlayer"
 isTapped = false
 classification = "normal"
 blue = 1
 isMarked = false
 isInCombat = false
 IsInterrupted = false
 threatSituation = "LOW"
 class = "WARLOCK"
 IsSoftFriendTarget = false
 threatValue = 0
 reaction = "FRIENDLY"
 green = 0
 health = 1604526
 isRare = false
 type = "PLAYER"
 isCasting = false
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'style' (a nil value)"
COLOR_ROLE = <table> {
 a = 0.700000
 b = 1
 g = 1
 r = 1
}
SUBTEXT_FUNCTIONS = <table> {
}
Addon = <table> {
 IS_WRATH_CLASSIC = false
 Theme = <table> {
 }
 TotemCreatureType = "Totem"
 AurasFilterMode = <table> {
 }
 IS_CATA_CLASSIC = false
 ANCHOR_POINT_SETPOINT = <table> {
 }
 CVars = <table> {
 }
 THREAT_VALUE_TYPE = <table> {
 }
 Font = <table> {
 }
 WOW_USES_CLASSIC_NAMEPLATES = false
 IGNORED_STYLES = <table> {
 }
 PlatesByUnit = <table> {
 }
 Animations = <table> {
 }
 ThreatPlates = <table> {
 }
 ANCHOR_POINT_TEXT = <table> {
 }
 IS_TBC_CLASSIC = false
 MODE_FOR_STYLE = <table> {
 }
 TotemInformation = <table> {
 }
 ON_UPDATE_PER_FRAME = 0.001000
 CUSTOM_PLATES_GLOW_FRAMES = <table> {
 }
 Debug = <table> {
 }
 PlatesByGUID = <table> {
 }
 EventHandler = <table> {
 }
 LibUTF8 = <table> {
 }
 Logging = <table> {
 }
 PLATE_FADE_IN_TIME = 0.500000
 ANCHOR_POINT = <table> {
 }
 CASTBAR_INTERRUPT_HOLD_TIME = 1
 PlayerName = "Ûnsullied"
 TOTEMS = <table> {
 }
 SCRIPT_FUNCTIONS = <table> {
 }
 IS_MAINLINE = true
 ON_UPDATE_INTERVAL = 0.250000
 LibAceConfigRegistry = <table> {
 }
 LibAceConfigDialog = <table> {
 }
 IS_CLASSIC = false
 db = <table> {
 }
 WIDGET_EVENTS = <table> {
 }
 IGNORED_STYLES_WITH_NAMEMODE = <table> {
 }
 IS_CLASSIC_SOD = false
 Widgets = <table> {
 }
 CUSTOM_GLOW_WRAPPER_FUNCTIONS = <table> {
 }
 CUSTOM_GLOW_FUNCTIONS = <table> {
 }
 LEGACY_CUSTOM_NAMEPLATES = <table> {
 }
 TARGET_TEXTURES = <table> {
 }
 Cache = <table> {
 }
 LibCustomGlow = <table> {
 }
 DEFAULT_FONT = "Cabin"
 UIScale = 1
 ADDON_DIRECTORY = "Interface\AddOns\TidyPlates_ThreatPlates\"
 DEBUG = true
 BackdropTemplate = "BackdropTemplate"
 LibSharedMedia = <table> {
 }
 PlatesCreated = <table> {
 }
 Data = <table> {
 }
 DEFAULT_SMALL_FONT = "Arial Narrow"
 PlayerClass = "DRUID"
 GLOW_TYPES = <table> {
 }
 PlatesVisible = <table> {
 }
}

**Comment by Solaervrang** [comment]
6x ...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1032: attempt to index upvalue 'style' (a nil value)
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1032: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1018>
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1049: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1042>
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:628: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:603>
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:672: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:645>
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1381: in function `?'
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1302: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1301>

Locals:
(*temporary) = Texture {
 PixelSnapDisabled = true
}
(*temporary) = nil
(*temporary) = Texture {
 PixelSnapDisabled = true
}
(*temporary) = Texture {
 PixelSnapDisabled = true
}
(*temporary) = "attempt to index upvalue 'style' (a nil value)"
unit = <table> {
 IsSoftEnemyTarget = false
 guid = "Creature-0-4246-2444-5885-196153-00003E429A"
 isMouseover = false
 IsSoftInteractTarget = false
 IsFocus = false
 IsBossOrRare = false
 level = 71
 red = 1
 levelcolorRed = 1
 IsSoftTarget = false
 unitid = "nameplate3"
 name = "Osoria"
 isElite = true
 levelcolorBlue = 0
 isBoss = false
 healthmax = 5552750
 isTarget = false
 levelcolorGreen = 0.820000
 NPCID = "196153"
 TP_DetailedUnitType = "Neutral"
 isTapped = false
 classification = "elite"
 blue = 0
 isMarked = false
 isInCombat = false
 IsInterrupted = false
 threatSituation = "LOW"
 threatValue = 0
 IsSoftFriendTarget = false
 class = ""
 reaction = "NEUTRAL"
 green = 1
 health = 5552750
 isRare = false
 type = "NPC"
 isCasting = false
}
visual = <table> {
 absorbbar = Texture {
 }
 customtext = FontString {
 }
 healthbar = StatusBar {
 }
 healthborder = Frame {
 }
 Highlight = Frame {
 }
 threatborder = Frame {
 }
 skullicon = Texture {
 }
 eliteicon = Texture {
 }
 spellicon = Texture {
 }
 level = FontString {
 }
 name = FontString {
 }
 spelltext = FontString {
 }
 textframe = Frame {
 }
 eliteborder = Frame {
 }
 castbar = StatusBar {
 }
 raidicon = Texture {
 }
}
style = nil

**Comment by Solaervrang** [comment]
154x ...eTidyPlates_ThreatPlates/Functions/scale.lua:165: attempt to call field '?' (a nil value)
[string "@TidyPlates_ThreatPlates/Functions/scale.lua"]:165: in function `SetScale'
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1064: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1059>
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:633: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:603>
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:672: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:645>
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1381: in function `?'
[string "@TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1302: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1301>

Locals:
self = <table> {
 IS_WRATH_CLASSIC = false
 Theme = <table> {
 }
 TotemCreatureType = "Totem"
 AurasFilterMode = <table> {
 }
 IS_CATA_CLASSIC = false
 ANCHOR_POINT_SETPOINT = <table> {
 }
 CVars = <table> {
 }
 THREAT_VALUE_TYPE = <table> {
 }
 Font = <table> {
 }
 WOW_USES_CLASSIC_NAMEPLATES = false
 IGNORED_STYLES = <table> {
 }
 PlatesByUnit = <table> {
 }
 Animations = <table> {
 }
 ThreatPlates = <table> {
 }
 ANCHOR_POINT_TEXT = <table> {
 }
 IS_TBC_CLASSIC = false
 MODE_FOR_STYLE = <table> {
 }
 TotemInformation = <table> {
 }
 ON_UPDATE_PER_FRAME = 0.010167
 CUSTOM_PLATES_GLOW_FRAMES = <table> {
 }
 Debug = <table> {
 }
 PlatesByGUID = <table> {
 }
 EventHandler = <table> {
 }
 LibUTF8 = <table> {
 }
 Logging = <table> {
 }
 PLATE_FADE_IN_TIME = 0.500000
 ANCHOR_POINT = <table> {
 }
 CASTBAR_INTERRUPT_HOLD_TIME = 1
 PlayerName = "Ûnsullied"
 TOTEMS = <table> {
 }
 SCRIPT_FUNCTIONS = <table> {
 }
 IS_MAINLINE = true
 ON_UPDATE_INTERVAL = 0.250000
 LibAceConfigRegistry = <table> {
 }
 LibAceConfigDialog = <table> {
 }
 IS_CLASSIC = false
 db = <table> {
 }
 WIDGET_EVENTS = <table> {
 }
 IGNORED_STYLES_WITH_NAMEMODE = <table> {
 }
 IS_CLASSIC_SOD = false
 Widgets = <table> {
 }
 CUSTOM_GLOW_WRAPPER_FUNCTIONS = <table> {
 }
 CUSTOM_GLOW_FUNCTIONS = <table> {
 }
 LEGACY_CUSTOM_NAMEPLATES = <table> {
 }
 TARGET_TEXTURES = <table> {
 }
 Cache = <table> {
 }
 LibCustomGlow = <table> {
 }
 DEFAULT_FONT = "Cabin"
 UIScale = 1
 ADDON_DIRECTORY = "Interface\AddOns\TidyPlates_ThreatPlates\"
 DEBUG = true
 BackdropTemplate = "BackdropTemplate"
 LibSharedMedia = <table> {
 }
 PlatesCreated = <table> {
 }
 Data = <table> {
 }
 DEFAULT_SMALL_FONT = "Arial Narrow"
 PlayerClass = "DRUID"
 GLOW_TYPES = <table> {
 }
 PlatesVisible = <table> {
 }
}
unit = <table> {
 IsSoftEnemyTarget = false
 guid = "Creature-0-4246-2444-5885-196141-00013E42E4"
 isMouseover = false
 IsSoftInteractTarget = false
 IsFocus = false
 IsBossOrRare = false
 level = 70
 red = 1
 levelcolorRed = 1
 IsSoftTarget = false
 unitid = "nameplate4"
 name = "Obsidian Whelpling"
 isElite = false
 levelcolorBlue = 0
 isBoss = false
 healthmax = 55528
 isTarget = false
 levelcolorGreen = 0.820000
 NPCID = "196141"
 TP_DetailedUnitType = "Minus"
 isTapped = false
 classification = "minus"
 blue = 0
 isMarked = false
 isInCombat = false
 IsInterrupted = false
 threatSituation = "LOW"
 threatValue = 0
 IsSoftFriendTarget = false
 class = ""
 reaction = "NEUTRAL"
 green = 1
 health = 55528
 isRare = false
 type = "NPC"
 isCasting = false
}
(*temporary) = nil
(*temporary) = <table> {
 IsSoftEnemyTarget = false
 guid = "Creature-0-4246-2444-5885-196141-00013E42E4"
 isMouseover = false
 IsSoftInteractTarget = false
 IsFocus = false
 IsBossOrRare = false
 level = 70
 red = 1
 levelcolorRed = 1
 IsSoftTarget = false
 unitid = "nameplate4"
 name = "Obsidian Whelpling"
 isElite = false
 levelcolorBlue = 0
 isBoss = false
 healthmax = 55528
 isTarget = false
 levelcolorGreen = 0.820000
 NPCID = "196141"
 TP_DetailedUnitType = "Minus"
 isTapped = false
 classification = "minus"
 blue = 0
 isMarked = false
 isInCombat = false
 IsInterrupted = false
 threatSituation = "LOW"
 threatValue = 0
 IsSoftFriendTarget = false
 class = ""
 reaction = "NEUTRAL"
 green = 1
 health = 55528
 isRare = false
 type = "NPC"
 isCasting = false
}
(*temporary) = nil
(*temporary) = "attempt to call field '?' (a nil value)"
SCALE_FUNCTIONS = <table> {
}

**Comment by Solaervrang** [comment]
It's something with some of my tp profiles that makes it don't work. Tried with a fresh char now that does not use the default tptp profile. Then it worked fluently, but all my other customs + the default one does not work. Is there a way around this? Delete and install again i guess?

**Comment by Backupiseasy** [comment]
The above Lua error messages do not help. I would need the first one in the list of errors. The above ones are thrown almost always as a consequence of something else failing.

You can export the profile that does not work and post it here. Maybe that can help me to reproduce the error.

**Comment by Solaervrang** [comment]
Yes!! Thanks for the quick answers and fast updates <3 Working fluently now
