### ISSUE TITLE
Cannot customize status text ，BUG

### ISSUE THREAD

**Issue by h308676539** [Backupiseasy/ThreatPlates#549]
Message: Interface/AddOns/TidyPlates_ThreatPlates/Init.lua:207: attempt to call global 'LoadAddOn' (a nil value)
Time: Fri Aug 16 02:25:37 2024
Count: 1
Stack: Interface/AddOns/TidyPlates_ThreatPlates/Init.lua:207: attempt to call global 'LoadAddOn' (a nil value)
[string "@Interface/AddOns/Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Interface/AddOns/Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:619: in function <...ace/AddOns/Masque/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: self = <table> {
 initializequeue = <table> {
 }
 statuses = <table> {
 }
 embeds = <table> {
 }
 frame = AceAddon30Frame {
 }
 addons = <table> {
 }
 enablequeue = <table> {
 }
}
addon = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "TidyPlatesThreat"
 orderedModules = <table> {
 }
 baseName = "TidyPlates_ThreatPlates"
 enabledState = true
 defaultModuleState = true
}

Message: ...e/AddOns/TidyPlates_ThreatPlates/Functions/scale.lua:165: attempt to call field '?' (a nil value)
Time: Fri Aug 16 02:26:03 2024
Count: 1806
Stack: ...e/AddOns/TidyPlates_ThreatPlates/Functions/scale.lua:165: attempt to call field '?' (a nil value)
[string "@Interface/AddOns/TidyPlates_ThreatPlates/Functions/scale.lua"]:165: in function `SetScale'
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:1064: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:1059>
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:633: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:603>
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:689: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:682>
[string "@Interface/AddOns/TidyPlates_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua"]:419: in function <...s_ThreatPlates/TidyPlatesInternal/TidyPlatesCore.lua:410>

Locals: self = <table> {
 IS_WRATH_CLASSIC = false
 Theme = <table> {
 }
 TotemCreatureType = "图腾"
 AurasFilterMode = <table> {
 }
 IS_CATA_CLASSIC = false
 ANCHOR_POINT_SETPOINT = <table> {
 }
 CVars = <table> {
 }
 THREAT_VALUE_TYPE = <table> {
 }
 Font = <table> {
 }
 WOW_USES_CLASSIC_NAMEPLATES = false
 IGNORED_STYLES = <table> {
 }
 PlatesByUnit = <table> {
 }
 Animations = <table> {
 }
 ThreatPlates = <table> {
 }
 ANCHOR_POINT_TEXT = <table> {
 }
 IS_TBC_CLASSIC = false
 MODE_FOR_STYLE = <table> {
 }
 TotemInformation = <table> {
 }
 ON_UPDATE_PER_FRAME = 0.008350
 CUSTOM_PLATES_GLOW_FRAMES = <table> {
 }
 Debug = <table> {
 }
 PlatesByGUID = <table> {
 }
 EventHandler = <table> {
 }
 LibUTF8 = <table> {
 }
 Logging = <table> {
 }
 PLATE_FADE_IN_TIME = 0.500000
 ANCHOR_POINT = <table> {
 }
 CASTBAR_INTERRUPT_HOLD_TIME = 1
 PlayerName = "贝尔娜缇塔"
 TOTEMS = <table> {
 }
 SCRIPT_FUNCTIONS = <table> {
 }
 IS_MAINLINE = true
 ON_UPDATE_INTERVAL = 0.250000
 LibAceConfigRegistry = <table> {
 }
 LibAceConfigDialog = <table> {
 }
 IS_CLASSIC = false
 db = <table> {
 }
 WIDGET_EVENTS = <table> {
 }
 IGNORED_STYLES_WITH_NAMEMODE = <table> {
 }
 IS_CLASSIC_SOD = false
 Widgets = <table> {
 }
 CUSTOM_GLOW_WRAPPER_FUNCTIONS = <table> {
 }
 CUSTOM_GLOW_FUNCTIONS = <table> {
 }
 LEGACY_CUSTOM_NAMEPLATES = <table> {
 }
 TARGET_TEXTURES = <table> {
 }
 Cache = <table> {
 }
 LibCustomGlow = <table> {
 }
 DEFAULT_FONT = "默认"
 UIScale = 1
 ADDON_DIRECTORY = "Interface\AddOns\TidyPlates_ThreatPlates\"
 DEBUG = true
 BackdropTemplate = "BackdropTemplate"
 LibSharedMedia = <table> {
 }
 PlatesCreated = <table> {
 }
 Data = <table> {
 }
 DEFAULT_SMALL_FONT = "默认"
 PlayerClass = "HUNTER"
 GLOW_TYPES = <table> {
 }
 PlatesVisible = <table> {
 }
}
unit = <table> {
 IsSoftEnemyTarget = false
 guid = "Creature-0-3905-0-150-114832-00003D3C76"
 isMouseover = false
 IsSoftInteractTarget = false
 IsFocus = false
 IsBossOrRare = false
 level = 70
 red = 1
 levelcolorRed = 1
 IsSoftTarget = false
 unitid = "nameplate2"
 name = "PvP训练假人"
 isElite = false
 levelcolorBlue = 0
 isBoss = false
 healthmax = 111055
 isTarget = false
 levelcolorGreen = 0.820000
 NPCID = "114832"
 TP_DetailedUnitType = "Tapped"
 isTapped = true
 classification = "normal"
 blue = 0
 isMarked = false
 isInCombat = false
 IsInterrupted = false
 threatSituation = "LOW"
 threatValue = 0
 IsSoftFriendTarget = false
 class = ""
 reaction = "NEUTRAL"
 green = 1
 health = 1
 isRare = false
 type = "NPC"
 isCasting = false
}
(*temporary) = nil
(*temporary) = <table> {
 IsSoftEnemyTarget = false
 guid = "Creature-0-3905-0-150-114832-00003D3C76"
 isMouseover = false
 IsSoftInteractTarget = false
 IsFocus = false
 IsBossOrRare = false
 level = 70
 red = 1
 levelcolorRed = 1
 IsSoftTarget = false
 unitid = "nameplate2"
 name = "PvP训练假人"
 isElite = false
 levelcolorBlue = 0
 isBoss = false
 healthmax = 111055
 isTarget = false
 levelcolorGreen = 0.820000
 NPCID = "114832"

**Comment by Backupiseasy** [comment]
This should be fixed now in release 12.0.8.

**Comment by h308676539** [comment]
> This should be fixed now in release 12.0.8.

thank you
