### ISSUE TITLE
Totem Updates

### ISSUE THREAD

**Issue by Squimbert** [Backupiseasy/ThreatPlates#550]
Stoneskin Totem was replaced with Stone Bulwark Totem (ID 59712).  Needs to be changed in Totems section.

There is also no such thing as Fire Elemental Totem in Retail.

**Comment by Backupiseasy** [comment]
You are right. But the ID for Stone Bulwark Totem seems to be 108270 - at least that's what I find on Wowhead: https://www.wowhead.com/spell=108270/stone-bulwark-totem

**Comment by Squimbert** [comment]
![StoneBulwarkID](https://github.com/user-attachments/assets/ebbd2c21-0e16-44a1-bdae-dd6cf908e5c6)
The ID of the Totem itself is 59712, as shown on the tooltip in my screenshot (right side of screen).  The ID of the spell that summons the totem is 108270.

**Comment by Backupiseasy** [comment]
I went to all Shaman totems and updated the list. Hopefully, I did not miss anything. I removed Tranquil Air Totem, Skyfure Totem, Windfure Totem, and Stoneskin Totem as these should no longer be available. 

I also added Stone Bulwark Totem, the icon for Surging Totem, and Totem of Wrath.
