### ISSUE TITLE
Healthbar mode class coloring applying to arena teamates, even though its disabled

### ISSUE THREAD

**Issue by sethiano** [Backupiseasy/ThreatPlates#559]
Hi!

Awesome addon!

Healthbar mode class coloring seems to be applying to arena teamates, even though its disabled.

In BGs all teamates are green as expected, but when I go into Arena, my teamates are still being class colored.

Thoughts?

**Comment by Backupiseasy** [comment]
This has been reported several times, but I was never able to reproduce this. Can you verify that coloring by target marker is enabled or that you don't put target marker on your teammates? I know that this caused confusion for me while testing as I mistook these colors for class colors.

**Comment by sethiano** [comment]
Thanks for getting back to me, and thanks for such an awesome addon!

I appreciate you!

I didn't see an option to enable the color by target markers, but I did see all the different color sections for each marker, so I turned them all to green (00FF00) and everything appears to be working now in skirmishes. I will try shuffle later when I am not at work and get back to you, but it looks like that was it.

I saw this in shuffle arena's which I believe automatically marks your teamates with markers.

TYVM!

Also, PS.

I believe the creator of FrameSort is trying to get a hold of you. FrameSort is an awesome addon, but it doesn't look like it is "sorting" the TP arena widget for replacing names with 1 2 3 in arena. He said he was going to try to reach out to the TP creator but hadn't had any success.

Thank you for all you do!

I will get back to you with the shuffle update later tonight.

**Comment by sethiano** [comment]
shuffles work fine now that all colors are set to green for markers. tytyty!

**Comment by Backupiseasy** [comment]
You can disable coloring by target marker. The option to disable it is (well hidden, it seems 😄 ) under General - Target Markers - Color Healthbar by Target Marks in Healthbar View. D

BTW, the newest beta for 12.1.0 now supports FrameSort, see https://github.com/Backupiseasy/ThreatPlates/pull/560.

**Comment by sethiano** [comment]
I finally found the coloring by target marker, TYTY!

Also TYTYTYTYTYT SO MUCH FOR THE FRAME SORT SUPPORT!!!!

Now I can use the arena 123 names in TP.

I really appreciate you!!!!

I hope you have a wonderful and blessed weekend!

**Comment by Backupiseasy** [comment]
You have to thank https://github.com/[Verubato](https://github.com/Verubato) for the support. He created the pull request add did all the work. Have fun playing!

**Comment by sethiano** [comment]
Hey @verubato \ @Backupiseasy just wante to let you know, I Just tested using Framesort /w TP arena numbers and hide names, and it still doesn't seem to be sorting the arena numbers above the name plates.

I went against a mage war (mage was 1 in arena frames and war was 2) because thats how i set it up in frame sort, but in the actual game, the warrior had the 1 above his name plate and the mage had the 2.

not sure who this would go to for support.

please let me know if i can add any more relevant info

tytyty!

**Comment by Verubato** [comment]
Hey man, do you have the new "Use FrameSort" option checked in the ThreatPlates arena widget area?

**Comment by sethiano** [comment]
Oh, I missed that. I didn't realize it was in the TP settings, derp. let me
test. ty!

-Seth Cowell-

**Comment by sethiano** [comment]
@Verubato Hrm... i just re-updated TP, and looked in the arena widget area and there is no use framesort option =/

**Comment by Verubato** [comment]
Update to the beta version:

![image](https://github.com/user-attachments/assets/182df09c-6fdf-410b-b2a8-3768015fe0d2)

**Comment by sethiano** [comment]
It fixy =) TYTY! <3 Sorry about that.

This is amazing!

THANK YOU BOTH!!!!!!
